Feature/go to file autotype suggestions
codefori/vscode-ibmi pull request #1242
Opened 2023-04-17 07:49 UTC by sebCIL

### Changes

Go to file...button. Autotype suggestions as you typing path to source file.
[Initial issue](https://github.com/halcyon-tech/vscode-ibmi/issues/1051)

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [X] **for feature PRs**: PR only includes one feature enhancement.

2023-04-17 11:31 UTC, chrjorgensen commented on src/instantiate.ts
> +                resultSet = await content!.runSQL(`SELECT SYSTEM_TABLE_NAME, TEXT_DESCRIPTION FROM QSYS2.SYSFILES WHERE SYSTEM_TABLE_SCHEMA = '${selectionSplit[0]}' AND FILE_TYPE = 'SOURCE' and syste
Please use `QSYS2.SYSTABLES` instead of `SYSFILES`- the latter is a new contruct and may not be available on the server connected to by the user.

```suggestion
                resultSet = await content!.runSQL(`SELECT SYSTEM_TABLE_NAME, TEXT_DESCRIPTION FROM QSYS2.SYSTABLES WHERE SYSTEM_TABLE_SCHEMA = '${selectionSplit[0]}' AND FILE_TYPE = 'S
```

2023-04-17 11:53 UTC, chrjorgensen requested changes
@sebCIL Thank for this PR! 👍 

I just gave it a spin and have these comments / questions:

- You use SQL but does not consider the configuration setting `enableSQL`. If this is disabled, you can't use SQL - and maybe the auto-suggest function has to be disabled, if you have no other way to get the list?
- You retrieve the list values from the SQL metadata tables - but these are in CCSID 37 (US) and does not take the user language into consideration. See the `getMemberList` function to see an example how to handle this. As is now, I get the following: 
![billede](https://user-images.githubusercontent.com/13275072/232470265-e3eb79e1-ca21-4837-8d2c-681010e8f792.png)
- Beware of the performance: You call the server each time the user enters a key after the first three characters in the name! The server may be slow and could make this client slow for the user. I see three options:
  - Keep the SQL as is and simply filter from the first `SELECT` - you already have the complete list.
  - Put a `LIMIT x` on the SQL to reduce the date returned.
  - Maybe an async call to SQL to collect the list in the background (don't know if it's possible).
- Since this could have a significant impact on the `Go to file` function, it should be a setting in the server configuration, so the user can enable or disable it as appropriate,
- If you can make the auto-suggest perform, you could reduce the required number of characters before auto-suggest is activated. Depending on the naming convention in place, three characters could be too many and make this function useless. Maybe the setting mentioned previously could be the number of characters required?
- Haven't you switched the member and file variables somewhat? In `case 2` you use member variables and in `case 3` you use file variables. I think it should be the other way around, right? Not that it has any influence on the function, it just makes the code confusing.

@worksofliam @sebjulliand Any comments (to the comments)? 😄

2023-04-18 12:45 UTC, sebCIL commented
Thanks for the feedback, I'm looking into it

2023-04-27 11:34 UTC, sebCIL commented
Ok, i made some changes.

What do you think about it?

2023-05-02 22:37 UTC, chrjorgensen requested changes
@sebCIL Good effort! I like your idea of caching beforehand - and even though it took almost ten seconds to cache the libraries on one of our systems and the `Go to File` dialog was shown, this is acceptable since I can (eventually) disable autosuggest for that system. I also like it now handles the variant characters correctly instead of showing `#@$`.

There are some problems producing a correct filtered list - see an example here:

![billede](https://user-images.githubusercontent.com/13275072/235799226-4425639c-0c3f-4eb0-ae05-88091efd6833.png)

Maybe the list parts should be sorted and filtered individually and combined in the end?
The `Clear list` should not be included in the filtered list.

Even though it is not mandatory and we all have our individual preferences, please follow the consensus in this project and add a semicolon to your statements - to indicate end of statement!

2023-05-02 22:37 UTC, chrjorgensen commented on src/instantiate.ts
> +            if (selection === `Clear list`) {
This should not be conditioned by `selectionSplit.length === 3`!
As is now, if I select `Clear list` without having entered a three part name, I get the following:

![billede](https://user-images.githubusercontent.com/13275072/235795997-2b364240-4a35-4491-877a-cd0294d8aceb.png)

and the list is still there the next time I select `IBM i: Go to File...`.

EDIT: Just noted that `Clear list` is not even there when the list is being filtered!

2023-05-02 22:37 UTC, chrjorgensen commented on src/instantiate.ts
> +                  label: 'Sources member',
```suggestion
                  label: 'Members',
```

To be consistent...

2023-05-03 11:01 UTC, chrjorgensen requested changes

2023-05-03 11:01 UTC, chrjorgensen commented on package.json
> +					"description": "Number of characters to enter before suggesting Library / Source file / Member when typing path to source file. (-1 to disable)"
And since you actually only test `goToFileAutoSuggest` for values greater than or equal to zero, you should make this configuration setting a boolean.

2023-05-03 11:19 UTC, chrjorgensen commented on package.json
> +					"description": "Number of characters to enter before suggesting Library / Source file / Member when typing path to source file. (-1 to disable)"
See below if this setting is needed at all...

2023-05-03 11:20 UTC, chrjorgensen commented
@sebCIL One important thing that I forgot to mention: The `Go to File...` handles both members and streamfiles!
So your autosuggest should not run when the value starts with `/`.

I also got some ideas that you may include if you like them:
1. When you cache libraries, files and members, you could write a message in the bar, e.g. "Caching libraries..." before you start your SQL, and remove the message when the cache is complete. This would tell the use why the dialog does not show immediately for long running SQL's.
2. When navigating to a library or file, the user may not always know the files or members in the library or file. If the user enters `*` immediately after the ´/´, you could show the whole list (and remove the `*` from the value). That way the user can see the content and start filtering. Actually a kind of ad-hoc object filter!

Thinking more on the `*` in idea 2... this could actually be a trigger for the autosuggest! So if you implement this, there is no need for a configuration setting at all... a better solution for the user, I think... WDYT?

Keep up the great work - this is going to be an awesome feature!

2023-05-03 11:29 UTC, chrjorgensen requested changes

2023-05-03 11:29 UTC, chrjorgensen commented on src/instantiate.ts
> +              if (listFile.length === 0) {
To me it seems like the cache is not cleared when the library changes?

2023-05-03 11:29 UTC, chrjorgensen commented on src/instantiate.ts
> +              if (listMember.length === 0) {
Same as above - is the member list cleared when the source file changes?

2023-05-04 11:34 UTC, sebCIL commented on package.json
> +					"description": "Number of characters to enter before suggesting Library / Source file / Member when typing path to source file. (-1 to disable)"
> And since you actually only test `goToFileAutoSuggest` for values greater than or equal to zero, you should make this configuration setting a boolean.

I confirm that I test the value to compare it to the number of characters entered : 
`if (selectionSplit[1].length >= goToFileAutoSuggest) {`

Not sure a boolean would be enough !?

2023-05-04 11:37 UTC, sebCIL commented on package.json
> +					"description": "Number of characters to enter before suggesting Library / Source file / Member when typing path to source file. (-1 to disable)"
> You created a global setting, not a connection setting... wink Please change it into a connection setting.
> 
> For an example of a connection setting, search for `showDescInLibList`.

Ok, I moved it.

2023-05-15 11:05 UTC, sebCIL commented
> Thinking more on the `*` in idea 2... this could actually be a trigger for the autosuggest! So if you implement this, there is no need for a configuration setting at all... a better solution for the user, I think... WDYT?

This is a good idea, I'll try to implement it.

2023-05-18 12:40 UTC, sebCIL commented
I made some changes, is it better?

2023-05-26 22:27 UTC, chrjorgensen commented
@sebCIL Sorry for the delay - hope to make a review this weekend. Thanks!

2023-06-05 20:22 UTC, chrjorgensen submitted a review, later dismissed
@sebCIL Thanks for the changes - and sorry for the delay! I have made a thorough review because of the long break with some comments.

Looking forward to get this functionality in the extension! :smile:

2023-06-05 20:22 UTC, chrjorgensen commented on src/instantiate.ts
> +          const asteriskIndex = quickPick.value.indexOf(`*`) ;
Would it be better if you remove the `*` typed after filling the list with possible values? This would indicate to the user that the `*` is not part of the name. I see that you remove it when the user selects from the list, but it's probably better to remove it asap.

I wonder what happens when the `*` is kept - will the code be run at every keystroke and query the server?

2023-06-05 20:22 UTC, chrjorgensen commented on src/instantiate.ts
> +                    label: 'Sources files',
```suggestion
                    label: 'Source files',
```

2023-06-05 20:22 UTC, chrjorgensen commented on src/instantiate.ts
> +        quickPick.placeholder = `Caching...`;
Setting `quickPick.placeholder` at this point does not seem to work - I don't see it... probably because the dialog is not yet shown.

2023-06-05 20:22 UTC, chrjorgensen commented on src/instantiate.ts
> +                // Create cache
You should clear the member cache at this point - or it will not be updated when the source file changes...

2023-06-08 08:51 UTC, sebCIL commented on src/instantiate.ts
> +        quickPick.placeholder = `Caching...`;
This is a test I forgot to remove.

2023-06-08 08:53 UTC, sebCIL commented on src/instantiate.ts
> +          const asteriskIndex = quickPick.value.indexOf(`*`) ;
I don't know how to remove the `*` ,because if do that, the `quickPick.onDidChangeValue` function will be recalled.

2023-10-05 12:34 UTC, chrjorgensen commented
@sebCIL Thanks for following up on this PR! It could help solve some issues that users are facing, e.g. #1563. I will review it this week, hopefully.

2023-11-22 15:42 UTC, chrjorgensen commented on src/instantiate.ts
> +          const asteriskIndex = quickPick.value.indexOf(`*`) ;
Seems like the * is not a problem. We'll leave it here.

2023-11-22 15:44 UTC, chrjorgensen reviewed
@sebCIL Sorry for taking so long - tested it again and it is looking good! 👍
I discovered that this feature is awesome and missed when I switched back to the master branch. I hope to include it in the upcoming release or the next one.

2023-11-22 15:47 UTC, chrjorgensen commented
@worksofliam I would very much like to have this awesome (but delayed - my fault!) feature included in the next release.

Will you give it a spin with some fresh eyes? 👀

2023-11-22 15:48 UTC, worksofliam commented
@chrjorgensen yup!! Let's stick it into the 2.5.0 milestone and I will review it asap.

2023-11-22 15:49 UTC, chrjorgensen reviewed
No comments - looking good!

2023-11-22 15:51 UTC, chrjorgensen commented
@worksofliam Already in the 2.5.0 milestone - you can review... Thanks! 😃

2023-11-22 17:44 UTC, chrjorgensen commented
@worksofliam Hold it for a minute - I found an error and will fix it...

2023-11-22 19:06 UTC, chrjorgensen commented
@worksofliam Fixed - go ahead with your review when you feel like it... 😃

2023-11-22 19:28 UTC, sebCIL commented
> @sebCIL Sorry for taking so long - tested it again and it is looking good! 👍 I discovered that this feature is awesome and missed when I switched back to the master branch. I hope to include it in the upcoming release or the next one.

No problem !
Thanks for your feedback.

2023-11-22 19:34 UTC, chrjorgensen commented
@sebCIL I fixed one small issue in commit https://github.com/codefori/vscode-ibmi/pull/1242/commits/4e44f2e8806d735b48016deecfe1b398ed57081e - but have now discovered, that the branch is so far behind master, that we need to squash and rebase the branch on master.

Do you want to do it yourself? It's **urgent** if you want the change merged before the next release!

Or I can do it - but then there's a risk that I will be shown as author (not sure how git will react on this).
You will of course get all credit in the release notes!

2023-11-23 22:24 UTC, chrjorgensen commented
@sebCIL I have squashed the commits in this PR into a single commit keeping you as the author. But I had to push the commit into a new PR #1680, which replaces this PR.

Hope you think it's okay.

We all learn along the way and I learned that long-running feature branches requires frequent merge or rebase on master branch, and, if there are many back and forth commits, squashing of the commits before publishing. I was actually surprised that in the end only one file was changed...

Keep up the good work!

@worksofliam I have converted this PR to draft to avoid accidental merging - please use and review PR #1680 instead of this one.

2023-11-23 22:49 UTC, worksofliam commented
@chrjorgensen I am guessing this PR should be closed if that is the case.

I can confirm that @sebCIL will still be an author if that's the case.

2023-11-23 22:51 UTC, closed without merging

2023-11-23 22:51 UTC, chrjorgensen commented
@worksofliam Okay, I will close this PR to avoid any confusion.

2023-11-24 07:03 UTC, sebCIL commented
> @chrjorgensen I am guessing this PR should be closed if that is the case.
> 
> I can confirm that @sebCIL will still be an author if that's the case.

Thx. 
The important thing is that the PR is integrated.