Improvement/member_resolves
codefori/vscode-ibmi pull request #1501
Opened 2023-08-24 14:50 UTC by worksofliam

### Changes

This adds an additional member resolve API, which will eventually deprecate the previous `memberResolves` API. This API depends on a brand new CL, which will inhherit the user profile iASP, which the current API does not.

I also created tests for this new API.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-08-24 18:32 UTC, worksofliam commented
Converted to draft as there may be an easier way with our existing API after all....

2023-08-30 08:06 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +        if (libraryList.currentLibrary) env[`&LIBL`] = libraryList.libraryList.join(` `);
Shouldn't this be `libraryList.libraryList`?

```suggestion
        if (libraryList.libraryList) env[`&LIBL`] = libraryList.libraryList.join(` `);
```

2023-08-30 08:09 UTC, chrjorgensen commented on src/languages/clle/getmbr.ts
> +    await connection.remoteCommand(
`remoteCommand` is deprecated and `runCommand` should be used instead:

```suggestion
    await connection.runCommand(
```

2023-08-30 08:31 UTC, chrjorgensen requested changes
@worksofliam I like this... Only a few minor issues... 😃

2023-11-19 01:48 UTC, worksofliam commented
I have thought of a better way to do this PR so I am going to close and have another branch for it in the future.

2023-11-19 01:48 UTC, closed without merging