Environment variable to manage debug settings
codefori/vscode-ibmi pull request #1595
Opened 2023-10-17 16:03 UTC by worksofliam

### Changes

* Adds `DEBUG_MANAGED` variable, and when `true` will:
   1. Hide the certificate UI in the connection settings
   2. Control secure mode based on if `DEBUG_CA_PATH` environment variable is set
   3. Hide debug setup walkthrough

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-10-18 02:43 UTC, william-xiang requested changes
Seems like the action on connected event at line 346 in `src/api/debug/index.ts` should also be changed. It does not need to check the remove cert or set the local cert for the managed environment.

2023-10-18 02:43 UTC, william-xiang commented on package.json
>  				"command": "code-for-ibmi.debug.start",
The commands `Start Debug Service` and `Stop Debug Service` should also be disabled in a managed environment.

2023-10-18 14:28 UTC, worksofliam commented on package.json
>  				"command": "code-for-ibmi.debug.start",
Done in a new commit.

2023-10-18 19:29 UTC, william-xiang approved these changes
Great job! Thank you.

2023-10-18 19:33 UTC, worksofliam commented
@codefori/core Any chance I can get some additional testing? Next step to ensure the debugger continues to work as normal. It is working good for me, but extra coverage never hurts.

2023-10-28 13:00 UTC, sebjulliand approved these changes
Code looks good and it works as expected.
Options are hidden when the env var is set to true. Everything works fine here.

2023-10-28 14:12 UTC, merged