Converted IFS browser
codefori/vscode-ibmi pull request #1611
Opened 2023-10-24 14:12 UTC by sebjulliand

### Changes
This PR converts the IFS Browser to TypeScript.

Also:
- Code has been refactored a bit
- Some commands are hidden from the command palette if not intended to be called from there
- IFS Shortcuts and Directory now have an icon
- A French translation has been fixed

### Checklist
* [x] have tested my change
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-11-06 13:50 UTC, worksofliam commented
@sebjulliand This is so fab! It's even less lines of code - I am going to run with this build for a few days and see how it goes.. will post back if I find any issues.

2023-11-18 18:17 UTC, worksofliam requested changes
Most functionality is looking good, other than the little issue that I can't open files. See my comments regarding a type issue.

Other things that are working:

* Download
* Rename / Move
* Search with valid results
* Delete object
* Open in terminal

2023-11-18 18:17 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +    this.iconPath = new vscode.ThemeIcon("folder-library");
Yes, I love this new icon!

2023-11-18 18:17 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +    this.contextValue = "directory";
Directory icon.. so simple yet so nice.

2023-11-18 18:17 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +  async getChildren(): Promise<BrowserItem[]> {
Moving the logic to fetch subitems to this right class is a nice tough.

2023-11-18 18:17 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +      arguments: [file]
It looks like this argument for `openEditable` is wrong. The `file` type is a missmatch to what is expected in `openEditable` (`string`).

<img width="529" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/cf6493d0-d409-4378-8bd0-279fdb50dfa7">

2023-11-18 18:27 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +      arguments: [file]
Shoot, how did I miss that?!

2023-11-18 18:52 UTC, sebjulliand commented
@worksofliam  Thanks for the nice feedback mate!
I fixed the call to `open editable`. It works fine now!

2023-11-18 19:19 UTC, worksofliam approved these changes
@sebjulliand Now we're looking excellent!!

I also testing some additional work to make sure shortcuts are working as expected.

Go ahead and merge whenever you're ready!

2023-11-18 19:21 UTC, sebjulliand commented
> @sebjulliand Now we're looking excellent!!
> 
> I also testing some additional work to make sure shortcuts are working as expected.
> 
> Go ahead and merge whenever you're ready!

Lovely! Thanks bud!

2023-11-18 19:21 UTC, merged