1475 fix home envvar
codefori/vscode-ibmi pull request #1621
Opened 2023-10-31 20:32 UTC by richardm90

### Changes

This PR relates to issue #1475.

I have modified `CompileTools.ts` so that it no longer sets the `HOME` variable, which goes on to set the PASE `HOME` environment variable. I have also added a new variable called `WORKDIR`, as a replacement for `HOME`.

In doing so the `HOME` variable is no longer available for use in actions.

**IMPORTANT** Is there a way to advise users that their actions will need updating?

I have also added another new variable called `FILEDIR` that gives you the remote directory that the file exists. This is extremely useful when you have multiple `Makefile`s in your project. You can have an action command such as `cd &FILEDIR && /QOpenSys/pkgs/bin/gmake`.

I have also updated the `varinfo.ts` and appropriate locale files with the action variable description changes. I used Google Translate on the French and Danish versions so if someone could check these that would be useful.

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-11-06 13:52 UTC, worksofliam commented on src/api/CompileTools.ts
> -      variables.set(`&HOME`, config.homeDirectory);
I don't think we should remove `&HOME` for now since a lot of people are using this today and we don't have a way to fix where it's used automatically.

2023-11-08 13:51 UTC, worksofliam commented on src/api/CompileTools.ts
> -      variables.set(`&HOME`, config.homeDirectory);
I think adding the `&HOME` variable back in, but removing it from the docs is a good idea. I think moving to `&WORKDIR` is the right idea for sure.

2023-11-11 15:21 UTC, worksofliam commented on src/api/CompileTools.ts
> -      variables.set(`&HOME`, config.homeDirectory);
@richardm90 I am going to write a review.

Let's keep `&FILEDIR` for sure, but let's also keep both `&WORKDIR` plus `&HOME` for compatibility reasons.

2023-11-11 15:22 UTC, worksofliam requested changes
Let's keep `&FILEDIR` for sure, but let's also keep both `&WORKDIR` plus `&HOME` for compatibility reasons.

When you have added `&HOME` back in (you don't need to add it back to the variable list UI) then I will review again.

2023-12-02 12:57 UTC, richardm90 commented
Hey @worksofliam was my update OK?

2023-12-27 13:29 UTC, richardm90 commented
@worksofliam , took me a little while as I was getting a problem when testing which must have been sorted in a recent commit as pulling down the latest has resolved my problem. I've updated the PR as suggested.

2024-01-30 12:33 UTC, worksofliam commented
@richardm90 I am sorry - every time I come around to look at this there are new conflicts. Any chance you can fix those and I can get another review in?

2024-01-30 13:52 UTC, richardm90 commented
@richardm90 , no problem, I'll get to it this week along with the comments you left on the other pr

2024-02-04 14:55 UTC, richardm90 reviewed
@worksofliam I've applied the latest changes

2024-02-09 23:25 UTC, worksofliam approved these changes
Looks good to me!

If you want to update this page for local development to include these changes, you're welcome: https://github.com/codefori/docs/blob/main/docs/pages/developing/local/actions.md

2024-02-09 23:25 UTC, merged