Add Ability to set Default Deployment Method Issue #1381
codefori/vscode-ibmi pull request #1652
Opened 2023-11-15 20:19 UTC by beckhamrryyaann

### Changes

This PR addresses issue #1381 .

The user is now able to set the default deploy method from the "Source" tab in the Connection Settings web view.  All methods are available to choose.  Once set, when user runs action that involves deploying, this PR will validate the default method is a usable option based on users current instance.  If all checks pass then the project will deploy without user needing to select the deploy method from the quick pick.  If there is an issue (default method is not usable) then the code will gracefully show the quick pick menu.

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [X ] **for feature PRs**: PR only includes one feature enhancement.

2023-11-16 15:44 UTC, worksofliam requested changes
Nice change! I left a comment about only showing options that are available. This might be tricky because we won't know what options are available when the user is not connected - this is because the connection settings can be edited offline.

What do you think @sebjulliand?

2023-11-16 15:44 UTC, worksofliam commented on src/webviews/settings/index.ts
> +          .addSelect(`defaultDeploymentMethod`, `Default Deployment Method`, [
This select makes sense, but when deploying we usually only show the user the options that are available to them. I am guessing we should do the same here.

https://github.com/codefori/vscode-ibmi/blob/2ae070eaff3d978e34063551fc01e26d382f7621/src/api/local/deployTools.ts#L58-L75

2023-11-16 16:39 UTC, beckhamrryyaann commented on src/webviews/settings/index.ts
> +          .addSelect(`defaultDeploymentMethod`, `Default Deployment Method`, [
I do not know what is available until the user connects.  It's like the which comes first ...egg or chicken parable!  :-)  What I decided to do was when the actual deploy action takes place I verify that the default method is a valid choice.  If not, it gracefully falls back as if the user has no default selected and shows the quick pick.  I could add a informational message with something like "default deploy method is not usable in your environment.  You will need to update your default deployment to a valid method."
https://github.com/beckhamrryyaann/vscode-ibmi/blob/e5a0a1bba5ae593fbcb6c700dd039e5e20482d1c/src/api/local/deployTools.ts#L75

But I will do whatever you and your team suggests...just let me know how you and @sebjulliand want me to proceed when you get chance.

2023-11-17 12:55 UTC, worksofliam commented on src/webviews/settings/index.ts
> +          .addSelect(`defaultDeploymentMethod`, `Default Deployment Method`, [
I actually think what you have now makes total sense. Show them all in the settings. but then complain when they deploy if the method is not available.

2023-11-17 12:57 UTC, worksofliam requested changes
Add some nit picks, but other than that it looks pretty good.

@sebjulliand you might want to check this one out too.

2023-11-17 12:57 UTC, worksofliam commented on src/api/Configuration.ts
> +    defaultDeploymentMethod: string;
Instead of type `string` can you use `DeploymentMethod | ''`?

2023-11-17 12:57 UTC, worksofliam commented on src/api/local/deployTools.ts
> +            method = (await vscode.window.showQuickPick(methods,
Perhaps when `defaultDeploymentMethod` is not blank, we need to show a warning here if the `defaultDeploymentMethod` is not available?

2023-11-17 20:22 UTC, beckhamrryyaann commented on src/api/Configuration.ts
> +    defaultDeploymentMethod: string;
done.

2023-11-17 20:22 UTC, beckhamrryyaann commented on src/api/local/deployTools.ts
> +            method = (await vscode.window.showQuickPick(methods,
warning is added.

2023-11-18 22:13 UTC, sebjulliand commented
@worksofliam I love it.
@beckhamrryyaann great job, I'll just have a few remarks.

2023-11-18 22:14 UTC, sebjulliand commented on src/api/local/deployTools.ts
> +            //methods.push({ method: "compare" as DeploymentMethod, label: `Compare`, description: `Synchronizes using MD5 hash comparison` });
I guess this wasn't meant to be commited?
```suggestion
            methods.push({ method: "compare" as DeploymentMethod, label: `Compare`, description: `Synchronizes using MD5 hash comparison` });
```

2023-11-18 22:15 UTC, sebjulliand commented on src/api/local/deployTools.ts
> +          let defaultDeploymentMethod = instance.getConfig()?.defaultDeploymentMethod as DeploymentMethod
You can (and should) use `const` here as `defaultDeploymentMethod` isn't changed after being set.
```suggestion
          const defaultDeploymentMethod = instance.getConfig()?.defaultDeploymentMethod as DeploymentMethod
```

2023-11-18 22:24 UTC, sebjulliand commented on src/api/local/deployTools.ts
> +          } else if (defaultDeploymentMethod as string !== '' && defaultDeploymentMethod !== undefined) { // default deploy method is set but not usable.
You can you reduce your test to this since you're testing if `defaultDeploymentMethod` is not `falsy`.
```suggestion
          } else if (defaultDeploymentMethod) { // default deploy method is set but not usable.
```

2023-11-18 22:26 UTC, sebjulliand approved these changes
It's a nice change!
Apart from a few style suggestions, I'd love to see the `compare` method back 🤣

2023-11-19 18:34 UTC, beckhamrryyaann commented
@sebjulliand oh my!! I sure am glad you caught that.  Some people might miss that!  I have put your fixes in place.  Thanks for your review.

2023-11-20 17:00 UTC, sebjulliand submitted a review, later dismissed
Looks good to me! That's very nice, thanks @beckhamrryyaann !
@worksofliam I'll let you have a last look and merge.

2023-11-20 20:28 UTC, worksofliam requested changes

2023-11-20 20:28 UTC, worksofliam commented on src/api/local/deployTools.ts
> +            method = (await vscode.window.showQuickPick(methods,
I don't really like that this assignment is duplicated in two else blocks. Perhaps only one else block is needed, with an additional if inside of it to check the valididity of `defaultDeploymentMethod`?

2023-11-20 20:28 UTC, worksofliam requested changes
Looking really good! Left one comment about some duplicate code which I think can be cleaner. 

Other than that, nice work!

2023-11-21 12:57 UTC, beckhamrryyaann commented on src/api/local/deployTools.ts
> +            method = (await vscode.window.showQuickPick(methods,
much cleaner now.

2023-11-21 19:05 UTC, worksofliam commented
Code looks good! I will get a review in today!

2023-11-21 19:47 UTC, worksofliam approved these changes

2023-11-21 19:47 UTC, worksofliam approved these changes
Works good to me! I am never taking it off of compare again haha. Thanks for a great PR!

2023-11-21 19:48 UTC, merged