Add code to escape member names when doing resolve
codefori/vscode-ibmi pull request #1655
Opened 2023-11-17 13:13 UTC by worksofliam

### Changes

Fixes issue where member resolves with dollar signs in the name (which sadly is very common) was not working because `$` is a special character in the shell.

Unit tests for `memberResolve` are continung to pass.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-11-18 22:45 UTC, sebjulliand commented on src/api/IBMiContent.ts
> +    const command = `for f in ${fixed.map(file => `/QSYS.LIB/${file.library.toUpperCase()}.LIB/${file.name.toUpperCase()}.FILE/${member.toUpperCase()}.MBR`).join(` `)}; do if [ -f $f ]; then echo $f;
Isn't `member` going to be a problem if it contains a `$` as well?
In which case it may be faster to escape it everywhere at once.
```suggestion
    const command = `for f in ${files.map(file => `/QSYS.LIB/${file.library}.LIB/${file.name}.FILE/${member}.MBR`.replace(/([$\\])/g,'\\$1').toUpperCase()).join(` `)}; do if [ -f $f ]; then echo $f; break; fi; done`;
```

2023-11-18 22:47 UTC, sebjulliand requested changes
Shouldn't the member name be escaped as well?

2023-11-19 01:41 UTC, worksofliam commented on src/api/IBMiContent.ts
> +    const command = `for f in ${fixed.map(file => `/QSYS.LIB/${file.library.toUpperCase()}.LIB/${file.name.toUpperCase()}.FILE/${member.toUpperCase()}.MBR`).join(` `)}; do if [ -f $f ]; then echo $f;
Oh yeah... I am totally blind. Good spot

2023-11-19 01:45 UTC, worksofliam commented on src/api/IBMiContent.ts
> +    const command = `for f in ${fixed.map(file => `/QSYS.LIB/${file.library.toUpperCase()}.LIB/${file.name.toUpperCase()}.FILE/${member.toUpperCase()}.MBR`).join(` `)}; do if [ -f $f ]; then echo $f;
Moved the file list into a new variable, purely for readability.

2023-11-20 20:03 UTC, worksofliam commented
@sebjulliand Take another look when you can - thanks!

2023-11-21 08:46 UTC, sebjulliand approved these changes
Perfect; code is clear and it works fine! Let's merge.

2023-11-21 08:46 UTC, merged