Add "Run on protected" option on Actions
codefori/vscode-ibmi pull request #1664
Opened 2023-11-19 15:08 UTC by sebjulliand

### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/1400

This PR adds a new `Run on protected` attribute to Actions:
![Capture d’écran du 2023-11-19 16-04-49](https://github.com/codefori/vscode-ibmi/assets/11096890/5a485173-5bcc-4483-a50d-c560a41dbda0)

If this attribute is enabled, then the Action will be allowed to be selected and to run on read-only members or from protected filters.

Before this PR, no action was allowed to run on protected or read-only targets.

### Checklist
* [x] have tested my change

2023-11-20 20:09 UTC, worksofliam requested changes
Other than some label changes, code looks ok to me. Re-request my review when it's ready! This is a neat change.

2023-11-20 20:09 UTC, worksofliam commented on package.json
> +								"description": "If enabled, this Action will be allowed to run on protected/read-only targets."
I think we have used 'readonly' in labels, instead of 'read-only'

2023-11-20 20:09 UTC, worksofliam commented on src/locale/ids/da.ts
> +  'actions.workAction.runOnProtected':'Run on protected/read-only',
Same about 'readonly' here.

2023-11-21 08:35 UTC, sebjulliand commented
You're right @worksofliam ; the label we used was actually `read only` elsewhere.
@chrjorgensen may I request your expertise for the Danish translation? 😊

2023-11-21 19:55 UTC, worksofliam approved these changes
Works good for me! This is another nice UX change. You can see in this image that I have a locked member open and don't have any Actions available (as told by the error message).

<img width="1128" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/51ce8f04-0d6f-41eb-b19a-417390cb4b52">

In this screenshot you can see that I have one or more actions enabled in protected mode, and the list appears with them in correctly.

<img width="1128" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/57add4f2-5d24-40d2-8049-43bed95c391d">

@sebjulliand Perhaps we should wait for Christian to add the correct translation and also let him test too before this is merged?

Thanks and great stuff!

2023-11-21 20:59 UTC, worksofliam approved these changes
@chrjorgensen Thank you!!

@sebjulliand Over to you for a merge whenever you like 😄

2023-11-21 21:02 UTC, chrjorgensen approved these changes
@sebjulliand Beautiful feature - works in my tests. 😍 

I made the Danish translation (and fixed some typos). Approved! Merge, Captain! 😃

2023-11-21 21:14 UTC, sebjulliand commented
Thank you guys! You've been brilliant, as always!

2023-11-21 21:14 UTC, merged

2023-11-30 17:42 UTC, m-tyler commented
Thanks a million for this enhancement.  Makes my life easier when I don't have `*ALLOBJ` on my user profile.
A list of my actions I marked to run in protected mode.  I don't really care if the standard CRT* actions are marked up as we have a CMS tool that should create objects outside of the developer environment. 

![image](https://github.com/codefori/vscode-ibmi/assets/1353665/27403032-573b-4cc7-a932-fa92c00fea28)