Sanitize library names before running liblist command
codefori/vscode-ibmi pull request #1673
Opened 2023-11-20 23:53 UTC by chrjorgensen

### Changes

This PR will fix the error described in issue #1672.
It will also fix errors in other library list commands:
- show an error when changing current library, if the new current library name starts with `#`
- don't allow non-existing libraries with name starting with `#` when changing the library list

### Checklist

* [x] have tested my change
* [x] eslint is not complaining

2023-11-21 20:00 UTC, worksofliam requested changes

2023-11-21 20:00 UTC, worksofliam commented on src/views/LibraryListView.ts
> +import { Tools } from "../api/Tools";
Unused import was added.

2023-11-21 20:02 UTC, worksofliam requested changes
I'd consider this a high impact change since it is used by a lot of our extension (and others!).

The tests are passing and things are working as normal.

Other than the unused import, the code and functionality works good.

Optionally, if you felt inclined, I'd love to see a new test case to show that it works with libraries that start with `#`.

2023-11-21 21:08 UTC, chrjorgensen commented on src/views/LibraryListView.ts
> +import { Tools } from "../api/Tools";
Ups - a leftover from when I thought I should sanitize library names in this module. Fixed!

2023-11-21 22:18 UTC, chrjorgensen commented
@worksofliam I'm currently working on some tests - which revealed some defects with the handling of '$'!
We have IT auditing (💩) at work tomorrow, but I hope to have some fixes ready tomorrow evening or soon after...

2023-11-22 12:43 UTC, chrjorgensen commented
@worksofliam I fixed errors for sanitizing names with '$' and validating library list with sanitized names - and finally added some tests to verify library name sanitizing. Please have another go...

2023-11-27 16:34 UTC, worksofliam approved these changes
Looking good @chrjorgensen! Thanks for your work here.

2023-11-27 16:34 UTC, merged