Feature/local_improvements_2
codefori/vscode-ibmi pull request #1723
Opened 2023-12-14 02:56 UTC by worksofliam

### Changes

* [x] New optional feature to automatically create a branch library when switching/creating a branch
* [x] Variables now appear in `actions.json`, making it easier to understand the content
* [ ] Library objects are browsable in the Object Browser

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-12-21 21:59 UTC, Wright4i requested changes
@worksofliam see 3 pending code comments. Thanks!

2023-12-21 21:59 UTC, Wright4i commented on package.json
> +					"description": "Used in conjuction with git. When the branch changes, prompt the user if they would like a new branch library for this branch."
Would like to see this mention the VSxxxxxxxx generated name somehow.

2023-12-21 21:59 UTC, Wright4i commented on src/api/local/git.ts
> +            .catch(err => {
Fails to catch when you are not authorized to create the library and will prompt you to make a filter anyway, which then doesn't work because of the failed create command.
![image](https://github.com/codefori/vscode-ibmi/assets/93156666/5a8b637d-9795-4f3f-941c-ea7a5eeab88e)

2023-12-21 21:59 UTC, Wright4i commented on src/api/local/git.ts
> +      const initRepo = gitApi.getRepository(workspaceFolder.uri);
I don't know if this is a bug or I am just stupid, but I had a hell of a time trying to get this to not return null for a git report I initialized in vscode as part of the review. I did a lot of googling, made sure it was actually a repo, had commits, folder authority was good, re-opened the repository, was definitely in my workspace, tried different file paths and stepped through on debug making sure the uri was good and it was. 

I was able to continue my testing though after cloning a git repo and opening that as my workspace. So I'm completely OK with calling the above user-error or a problem on my machine, but I'd like you to try making a new repo and see if you see the same issue.

2023-12-23 15:57 UTC, worksofliam commented on src/api/local/git.ts
> +            .catch(err => {
Resolved. I wasn't handling the error correctly.

2023-12-23 15:59 UTC, worksofliam commented on src/api/local/git.ts
> +      const initRepo = gitApi.getRepository(workspaceFolder.uri);
Yeah, that makes sense. `setupGitEventHandler` is called when the extension is loaded. When the extension is loaded, but it's not a git repo, then any action against it is ignored. So if you load the extension, and it's a git repo, we listen to it. For now, I think this is expected behaviour.

2023-12-23 16:00 UTC, worksofliam commented
@Wright4i I fixed two of the three issues you raised - thanks for a great review.

Sadly, we need #1741 to be merged into this branch for the fixes to take affect right now. I will re-request a review when that is done.

2023-12-23 22:16 UTC, Wright4i approved these changes
Fixes look good. Approved

2023-12-24 01:10 UTC, worksofliam commented
@Wright4i Requesting your review again! I fixed the issue you described above: we can now detect when a repo is initialized and handle those branch changes too!

Please try again and let me know what you think.

2023-12-26 15:28 UTC, Wright4i approved these changes
LGTM! Fix worked and prompted to create a library on a branch switch after creating a new git repo.
![image](https://github.com/codefori/vscode-ibmi/assets/93156666/11f1298d-c510-4f57-8df6-3f9a2f58e974)

2024-01-09 23:55 UTC, worksofliam commented
@Wright4i Any chance I can bother you to retest this again after a fairly large merge? The same tests as before would be fab. Thank you.

2024-01-12 20:12 UTC, Wright4i approved these changes
@worksofliam No issues with my tests after the merge & typo fix. Code looks solid. Good to go 👍

2024-01-17 15:14 UTC, merged