Fix error opening a specific member reference in Go To File
codefori/vscode-ibmi pull request #1733
Opened 2023-12-15 22:14 UTC by chrjorgensen

### Changes

This PR will fix issue #1732 by (re)adding the entered value to the list, thus allowing it to be selected (accepted).
This was a regression from the new member search in function Go To file.

### Checklist

* [x] have tested my change
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining

2023-12-22 22:57 UTC, worksofliam requested changes
Left one small suggestion. Code looks pretty good otherwise!

2023-12-22 22:57 UTC, worksofliam commented on src/instantiate.ts
> +                };
I am thinking this could be simpler than using `lastIndexOf` and `includes`.

I think we should use `path.parse(member)` here as it will take care of getting the name and extension out of the entered value correctly.

```
> member
'ABCD.RPGLE'
> path.parse(member)
{ root: '', dir: '', base: 'ABCD.RPGLE', ext: '.RPGLE', name: 'ABCD' }
> noext
'THEMBR'
> path.parse(noext)
{ root: '', dir: '', base: 'THEMBR', ext: '', name: 'THEMBR' }
```

2023-12-23 21:46 UTC, chrjorgensen commented on src/instantiate.ts
> +                };
Now uses `path.parse` instead...

2023-12-23 21:59 UTC, worksofliam requested changes
Only one real issue with casing, other than that it works as expected now!

2023-12-23 21:59 UTC, worksofliam commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
Looks like `selectionSplit` doesn't account for case, so if a lowercase value is provided, the rest of this code fails because it expects members in uppercase for the SQL statement.

```suggestion
            const selectionSplit = selection.toUpperCase().split('/');
```

2023-12-23 21:59 UTC, worksofliam commented on src/instantiate.ts
> +                const fullMember = await content!.runSQL(`
SQL statement makes sense. I wonder if it would be better (or faster?) to use `CHKOBJ` with the `MBR` parameter here? What do you think?

We have the `checkObject` API, but might need a new parameter for member.

2023-12-23 21:59 UTC, worksofliam commented on src/instantiate.ts
> +                const fullMember = await content!.runSQL(`
Also, makes sense if you want to leave it like this.

2023-12-23 22:07 UTC, chrjorgensen commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
The selection will always be in uppercase, if it's a member:
- if the member is entered by the user, the value is put in the list in uppercase
- if the member is from a search, it is in uppercase by SQL
So it should not be necessary to convert to uppercase. We also don't want to convert streamfiles to uppercase.

2023-12-23 22:10 UTC, chrjorgensen commented on src/instantiate.ts
> +                const fullMember = await content!.runSQL(`
I prefer the SQL - is already in use by the search.
And SQL returns the type, which can then be validated.
If the user specifies the member without type, it will be opened if found - if the type is specified, both name and type must match.

2023-12-23 22:12 UTC, worksofliam commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
Can you confirm this is user error then? I have all these lowercase listings in my quick pick from prior usage.

<img width="623" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/f65cac90-23fc-4dfd-8e39-64469d99f893">

2023-12-23 22:14 UTC, worksofliam commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
I also have this enabled, so it looks like it is adding lowercase names to the list! 
<img width="920" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/95ac565e-abb9-42fb-a73b-ff8abe35974d">

2023-12-23 22:16 UTC, worksofliam commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
Looks like it's this line of code storing the values, including as lowercase when that option is enabled: https://github.com/chrjorgensen/code-for-ibmi/blob/d863157505d93b76388c9c9092fee9c398375394/src/views/objectBrowser.ts#L216

2023-12-23 22:30 UTC, chrjorgensen commented on src/instantiate.ts
>              const selectionSplit = selection.split('/')
The uppercase issue has been fixed.

2023-12-23 22:37 UTC, worksofliam approved these changes
* My lowercase cache works now
* Search/filter still working as expected

Beautiful work @chrjorgensen!

2023-12-23 22:37 UTC, merged