Fix CRTLIB error checking when connecting + other error checkings
codefori/vscode-ibmi pull request #1741
Opened 2023-12-21 09:46 UTC by sebjulliand

### Changes
Fixes https://github.com/codefori/vscode-ibmi/issues/1739

This PR adds a method that will parse commands `stderr` into `IBMiMessages` to facilitate error analysis.
This helps checking what IBM i messages are returned after a command call and fixes some checking that only looked for the first returned message ID.

### Checklist
* [x] have tested my change

2023-12-21 21:09 UTC, chrjorgensen requested changes
@sebjulliand When connecting to PUB400, I get the following error:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/488a2fa5-5d47-4d7c-895d-be738d9c0240)

I checked, and there are no dataarea like that on PUB400...?

2023-12-21 21:25 UTC, sebjulliand commented
> @sebjulliand When connecting to PUB400, I get the following error:
> 
> I checked, and there are no dataarea like that on PUB400...?

@chrjorgensen The change I made doesn't impact this check. But it would mean that this call to `CHKOBJ` didn't return 0:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/73145953-d0dc-46f2-b24f-0b56f93a1b9c)

Do you have any more detail in debug, like the content of the `QCPTOIMPF` CommandResult?

2023-12-21 21:48 UTC, chrjorgensen commented
@sebjulliand It's the previously discussed error with `[[`:

```
"CPF9801:  Object QCPTOIMPF in library QSYS not found.\nqsh: 001-0019 Error found searching for command [[. No such path or directory."
```

2023-12-21 21:59 UTC, chrjorgensen commented
@sebjulliand This is the status after the `CRTLIB` command:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/c7399ce3-9868-44aa-9a6b-c4884307045f)

Should additional tests for message ID's be added? CPF0001?

2023-12-22 01:48 UTC, worksofliam commented
@chrjorgensen 

> I actually don't understand how the error code can be zero, when the command failed...!?

I don't think it can. This is likely my bad for sure!

2023-12-22 01:51 UTC, worksofliam commented
@chrjorgensen that is totally weird, but I'm guessing it's because of how runCommand returns the exit code. Defo got something to do with those brackets.

This line of code: https://github.com/codefori/vscode-ibmi/blob/7c7dfb42d6cbf7cf7cb43c36072a206ed32dbf33/src/api/CompileTools.ts#L663

2023-12-22 22:23 UTC, worksofliam commented
I have merged my PR into this one to make it easier. Now I am no longer getting the warning about the data area existing! 

@chrjorgensen back to you for some testing and I am going to do a quick code review too.

2023-12-22 23:22 UTC, sebjulliand reviewed
Works fine here on PUB400 and other systems.
Looks like we could merge!

2023-12-23 16:00 UTC, worksofliam commented
@sebjulliand I agree on the merge, but I am thinking we should let @chrjorgensen have another go through as well.

2023-12-23 16:02 UTC, worksofliam commented on src/api/IBMi.ts
> +        console.log(createdTempLib?.stderr);
Should this be taken out?

2023-12-23 16:18 UTC, sebjulliand commented on src/api/IBMi.ts
> +        console.log(createdTempLib?.stderr);
Agreed

2023-12-23 18:32 UTC, chrjorgensen commented on src/api/CompileTools.ts
> +                  `${`system ${GlobalConfiguration.get(`logCompileOutput`) ? `` : `-s`} "${command.replace(/[$]/g, `\\$&`)}" && exit $?`}`,
@worksofliam How can this work? AFAIK, `&&` make the `exit` only being run if the previous command runs successfully?

2023-12-23 18:58 UTC, worksofliam commented on src/api/CompileTools.ts
> +                  `${`system ${GlobalConfiguration.get(`logCompileOutput`) ? `` : `-s`} "${command.replace(/[$]/g, `\\$&`)}" && exit $?`}`,
You are completely right. I am taking out the `exit` in a new commit and the tests still pass.

2023-12-23 20:20 UTC, chrjorgensen approved these changes
@sebjulliand @worksofliam Working as expected - approved!

2023-12-23 20:20 UTC, merged