Feature/edit vs browse
codefori/vscode-ibmi pull request #1757
Opened 2024-01-04 15:04 UTC by sebjulliand

### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/1752

As discussed in https://github.com/orgs/codefori/discussions/1331, browsing/editing support could use a little love. This PR brings some enhancement to address what was discussed:

- A new `Open` sub-menu replaces the single `Browse` action in stream files/member's right click menu. The sub-menu offers to explicitly open a streamfile/member read-only or for editing.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/49b523b0-7a9e-4615-9211-eb02538c7832)
- A new global setting lets the user define what should be the open action by default when clicking on a streamfile/member to open it
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/6b94a93e-af63-4dd2-ac86-888a25c5a130)
- A new connection settings lets the user define `protected paths`: a comma-separated list of libraries and/or IFS paths that will always be opened read-only.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/1bdec1e9-182d-4e0c-a46b-4d271f0b47d5)

Under the hood, all the actions that open a streamfile/member now end up using `code-for-ibmi.openEditable` that holds all the logic for checking if the target should be opened read-only or not. This command has also be enhanced to allow to open a resource and highlight a range in the opened document.

### Checklist
* [x] have tested my change

2024-01-04 17:40 UTC, chrjorgensen requested changes
@sebjulliand Great PR - only a few issues:

- directory uppercase (see code comment)
- filter does not show the library is protected - only when the filter is marked as protected. Could this be done?

2024-01-04 17:40 UTC, chrjorgensen commented on src/webviews/settings/index.ts
> +                      .map((item: string) => item.trim().toUpperCase())
@sebjulliand You're uppercasing every item in the list, including IFS paths... this makes IFS paths never match and protect IFS directories (unless their name is in CAPITALS)...

Only library names should be transformed to uppercase...

2024-01-04 18:25 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +                      .map((item: string) => item.trim().toUpperCase())
Silly me...

2024-01-04 18:41 UTC, chrjorgensen commented on src/webviews/settings/index.ts
> +                      .map((item: string) => item.trim().toUpperCase())
Not as silly as me, who made PR #1756 without checking if it would collide with other PR's - like this! 😄 

Seems like I have to wait for this one and then remap my changes into the new version...

2024-01-04 18:53 UTC, chrjorgensen commented on src/webviews/settings/index.ts
> +                      .map((item: string) => item.trim().toUpperCase())
Oh, actually - maybe my PR came first anyway....! 😉

2024-01-04 19:11 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +                      .map((item: string) => item.trim().toUpperCase())
Yup, we'll merge yours first and then I'll take care of this one. That's only fair!

2024-01-04 19:14 UTC, sebjulliand commented
There you go @chrjorgensen :
- Only libraries will be uppercase when saving the protected paths setting
- Both IFS browser and Object browser will take into account the protected paths
- IFS browser will show a lock on folders that are protected (or parent of a protected folder)
- Changing the protected paths setting will automatically refresh the browsers to immediately protect what needs to be

2024-01-04 20:30 UTC, chrjorgensen commented
@sebjulliand Looking very good  and promising! 😍 

I will do some more testing tomorrow - before I'll approve this great enhancement.

2024-01-05 23:47 UTC, chrjorgensen approved these changes
@sebjulliand All is fine - as always with your PR's! :heart_eyes: 

Rebase and merge when appropriate...

2024-01-06 08:45 UTC, sebjulliand commented
> @sebjulliand All is fine - as always with your PR's! 😍
> 
> Rebase and merge when appropriate...

Will do! Thank you so much!

2024-01-06 08:55 UTC, merged