Fix error when referencing undefined parameters variable
codefori/vscode-ibmi pull request #1760
Opened 2024-01-05 07:41 UTC by krethan

### Changes

When parameters variable is undefined it is generating an error when trying to reference parameters.name. Added check to ensure parameters.name is defined before updating the connection information. There is also no need to update the connection information if parameters.name is undefined.

### Checklist

[*] have tested my change
[*] updated relevant documentation
[*] Remove any/all `console.log`s I added
[*] eslint is not complaining
[*] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
[*] **for feature PRs**: PR only includes one feature enhancement.

2024-01-05 07:42 UTC, krethan commented
2 commits as I updated the contributions.md seperately.

2024-01-05 23:59 UTC, chrjorgensen commented
Hi @krethan !

Thank you for your contribution to this project - really appreciated!

One question: How can I reproduce the error, that your change is fixing? I haven't seen this before...

2024-01-06 03:44 UTC, worksofliam commented
@chrjorgensen I believe this shows up in the debug console (during debug) or the developer consider (during runtime). I have seen this!

2024-01-06 06:11 UTC, krethan commented
When you try to open a connection parameters will be undefined and gives this error in the debug console: 

![image](https://github.com/codefori/vscode-ibmi/assets/9780893/fa740958-28af-4992-9795-958c25779188)

2024-01-09 23:47 UTC, worksofliam commented on src/api/Configuration.ts
> +      connections = getConnectionSettings();
Any chance this can be `const connections =` instead of using `let` above?

2024-01-09 23:47 UTC, worksofliam requested changes
@krethan I left one small request - otherwise, working as expected. Thanks!

2024-01-10 05:40 UTC, krethan commented
@worksofliam Changed the let to const and moved it into the if block. 

This issue is occuring when setting up the connection for the first time after the extension is installed. After a connection is successful this is not an issue anymore.

2024-01-10 14:43 UTC, worksofliam commented
Just retested and works as expected. This error had been lingering for a while, so it's nice to see it fixed. 

Thanks for your PR!

2024-01-10 14:44 UTC, worksofliam approved these changes

2024-01-10 14:44 UTC, merged