Delete password when private key is used
codefori/vscode-ibmi pull request #1767
Opened 2024-01-08 16:07 UTC by worksofliam

### Changes

There is a bug with starting the debugger if the user once used a password, but is now using a private key, as the user would never be prompted for the correct password when debugging.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2024-01-08 20:01 UTC, edmundreinhardt approved these changes

2024-01-09 16:19 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +                  context.secrets.delete(`${name}_password`);
It's an async call, we should await.
```suggestion
                  await context.secrets.delete(`${name}_password`);
```

2024-01-09 16:21 UTC, sebjulliand requested changes
It works as expected! Good job!
But `context.secrets` function are asynchronous, I'd suggest we `await` on them everywhere in the extension (here, but there are other places in the extension where `await` is missing too).

2024-01-09 23:49 UTC, worksofliam commented
@sebjulliand Ready for another review - thanks!

2024-01-10 08:38 UTC, sebjulliand approved these changes
Looking good now!
I added a commit to add `await` in some other places where the secret store is used, I hope you won't mind 😁
Feel free to merge whenever you want.

2024-01-10 14:31 UTC, merged