Enhance Object Browser filter's Object field
codefori/vscode-ibmi pull request #1780
Opened 2024-01-14 16:15 UTC by sebjulliand

### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/1779

This PR enhances the Object browser filter's `Object` field to allow to filter on multiple names, including generic ones.
- The field title is now Objects to reflect this change.
- Multiple names must be separated by commas.
- Names with an asterisk can be used to filter on names that start with (`XXX*`) or end with (`*XXX`)

![Code_BqD8HsWF1i](https://github.com/codefori/vscode-ibmi/assets/11096890/3aa6af94-d760-4cc4-a0f2-80a9153ebb60)

If the field contains only one name, `getObjectList`'s behavior remains unchanged. If multiple name filtering criteria are defined, then all the objects are listed first and then the actual filtering happens.

### Checklist

* [x] have tested my change
* [x] **for feature PRs**: PR only includes one feature enhancement.

2024-01-15 21:08 UTC, chrjorgensen requested changes
@sebjulliand As always a great enhancement from your hands! :heart_eyes: 

I have some comments besides the suggestions in the code:
- Previously `*ALL` was allowed as object name and returned all objects (like a single `*`). This does not work anymore. I guess that is okay, since the description says a single `*` will do the trick.
- When I specify a generic object name like `*C*` in the filter, nothing is returned. I guess your generic-test does not handle this? Maybe a regex test could solve this?

You know what's coming next... **_Can we have the same for members?!_** :rofl: 
Seriously, I'm convinced the users will ask for this - now they're given the option to have multiple objects in a filter.

We're still a bit behind RDi ("shh, don't mention the war!" :laughing:) in our filter options - in RDi you can specify a generic source file name linked to a generic member name and type, and have multiple of these groups in a filter. When I was thinking of coding this, that was my intention - to turn the object, member and type into a list, so the three would be linked together and had all to be met to be included in the output. This allows for more granular selection...

WDYT?

But still, a great enhancement...!!! :heart_eyes:

2024-01-16 12:57 UTC, sebjulliand commented
> @sebjulliand As always a great enhancement from your hands! 😍
> 
> I have some comments besides the suggestions in the code:
> ...
> WDYT?
> 
> But still, a great enhancement...!!! 😍

Thank you so much @chrjorgensen ! As always, your review is on point.
I'll look into the suggested changes and add support for *xxx* type of filter.

And then I'll apply the filtering logic to members and types; it should be fairly easy.

2024-01-16 13:02 UTC, sebjulliand commented on src/api/IBMiContent.ts
> +    let hasEndsWith = false;
It's used right after to check if at least one filter is a `ends with` kind of filter. In this case, even if there is one filter, the filtering logic (i.e. AFTER all the items are loaded) must be applied.

2024-01-16 13:03 UTC, sebjulliand commented on src/api/IBMiContent.ts
> +    const objects = filters.object?.split(',')
Yep, I'm going to add this capability. Thanks for the suggestion!

2024-01-16 15:07 UTC, worksofliam commented
@sebjulliand Since you are enhancing `getObjectList`, I would really love to see some additional tests to support these changes

2024-01-18 17:13 UTC, jkyeung commented
First, thank you for this enhancement. It truly transforms the usability of the filter.

Second, I want to amplify the point about the members: If I could only choose to have "advanced" filtering on objects or members (I realize this is not a true choice, just trying to illustrate), I would choose members. In any shop that uses source physical files, the members are where all the most important naming conventions happen. Everyone mainly sticks to the object names provided by IBM (QRPGLESRC, QCLSRC, etc.), and there are not too many of them. But there are usually hundreds or even thousands of members in a given source file, and every shop has their own naming system for them.

Finally, to that end, I think a regex option would be extremely useful, but only for those users who are comfortable with regex. It would be confusing to many users. So if it's too much trouble to handle multiple styles of wildcard, I would stick to the basics: either just something equivalent to regex's `.*` (like the current `*` most IBM i users are used to, or `%` in SQL's LIKE predicate), or that plus something equivalent to regex's `.` (like SQL's `_`). Those would cover most cases for most users.

I could imagine a setting, where you can choose regex or "basic IBM" or "SQL-style", especially if you're going to implement any of them using regex under the covers anyway.

2024-01-19 08:40 UTC, sebjulliand commented
Thanks for the feed @jkyeung !
I'm actually going to add support for regex in there, at every level (library, file and member) - we should end up with the same filtering ability as in RDi, but with regex support.

By default, filters will only support the `*` wildcard to keep it simple for most use cases and not confuse people. A checkbox in the filter definition will allow to turn on RegEx support if needed.

2024-01-19 16:51 UTC, jkyeung commented
> I'm actually going to add support for regex in there, at every level (library, file and member)

I can't wait!

> By default, filters will only support the `*` wildcard to keep it simple for most use cases and not confuse people. A checkbox in the filter definition will allow to turn on RegEx support if needed.

Perfect!

2024-01-24 15:22 UTC, sebjulliand commented
@codefori/core , you're on!
I updated the PR description to match what's done here. Let me know how it goes! 😄

2024-01-24 17:04 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)`], "LIBLIST");
The SQL statement is not correct:
```suggestion
      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)')`], "LIBLIST");
```

2024-01-24 17:12 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)`], "LIBLIST");
I think your command is missing a quote and parenthesis:

```suggestion
      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)')`], "LIBLIST");
```

2024-01-24 17:28 UTC, chrjorgensen commented on src/api/IBMiContent.ts
Why do you have a common table expression here? There are no WHERE clause in the CTE and it will become the product of _ALL_ files and members on the system.

I would suggest simply removing it:

```suggestion
    const statement =
      `SELECT
          rtrim(cast(a.system_table_schema as char(10) for bit data)) as LIBRARY,
          b.avgrowsize as RECORD_LENGTH,
          a.iasp_number as ASP,
          rtrim(cast(a.system_table_name as char(10) for bit data)) AS SOURCE_FILE,
          rtrim(cast(b.system_table_member as char(10) for bit data)) as NAME,
          coalesce(rtrim(cast(b.source_type as varchar(10) for bit data)), '') as TYPE,
          coalesce(rtrim(b.partition_text), '') as TEXT,
          b.NUMBER_ROWS as LINES,
          extract(epoch from (b.CREATE_TIMESTAMP))*1000 as CREATED,
          extract(epoch from (b.LAST_SOURCE_UPDATE_TIMESTAMP))*1000 as CHANGED
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
      Where LIBRARY = '${library}'
        ${sourceFile !== `*ALL` ? `And SOURCE_FILE = '${sourceFile}'` : ``}
        ${singleMember ? `And NAME Like '${singleMember}'` : ''}
        ${singleMemberExtension ? `And TYPE Like '${singleMemberExtension}'` : ''}
      Order By ${sort.order === 'name' ? 'NAME' : 'CHANGED'} ${!sort.ascending ? 'DESC' : 'ASC'}`;
```

2024-01-24 17:38 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`Create Table QTEMP.MEMBERSLST As (${statement}) With DATA`], "MEMBERSLST");
You have removed the `DSPFD` command completely and use SQL always, whether SQL is enabled or not.
Is this correct behavior? I've never really understood the purpose of having a toggle for using SQL or not... @worksofliam?

2024-01-24 17:42 UTC, worksofliam commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`Create Table QTEMP.MEMBERSLST As (${statement}) With DATA`], "MEMBERSLST");
I guess the original reasons for having the SQL toggle was in case users didn't have `db2util` or `db2` in QSH, but since we now use a system API, which I guess we can assume is always there, then maybe we can remove it one day?

2024-01-24 18:27 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`Create Table QTEMP.MEMBERSLST As (${statement}) With DATA`], "MEMBERSLST");
One day, hopefully - would make things easier...

2024-01-24 20:30 UTC, chrjorgensen commented on src/api/IBMiContent.ts
I get it now... finally... 😆

2024-01-24 20:49 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)`], "LIBLIST");
The command is executed when SQL is not enabled and library descriptions are enabled, and results in this error and an empty library list view:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/e934901e-96f9-4f12-bfe2-c34aa5140bf2)

2024-01-24 20:51 UTC, chrjorgensen commented on src/api/IBMiContent.ts
> +      results = await this.getQTempTable([`CALL QSYS2.QCMDEXC('DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(QTEMP/LIBLIST)`], "LIBLIST");
Fixed in commit [8887227](https://github.com/codefori/vscode-ibmi/pull/1780/commits/8887227ca3bb471be72cacbd33a31a148cc08ebf)

2024-01-24 21:29 UTC, chrjorgensen commented
@sebjulliand 🚀 🚀 🚀 🚀 🚀 - 5 out of 6 rockets because

- so far in my tests the simple filters work perfectly
- only the regex filter won't work for me - do you have an example?

Beautiful work, (IBM) Champ!! 😍

2024-01-25 10:22 UTC, sebjulliand commented
@chrjorgensen it runs better now! I fixed what needed to be and RegExp filtering is fine now 😄

2024-01-25 12:13 UTC, chrjorgensen requested changes
@sebjulliand Regexp works much better now! 😍 

One issue was found during testing: the regular express meta characters like `\d` (for digits) doesn't work, because the filter is changed to uppercase and the `\d` becomes `\D` - the reverse!

Can this be fixed? Maybe by not converting regex filter values to uppercase and filter with ignore-case flag? Only if it's easy - I could use `[0-9]` to achieve the same result. We could also check for any meta characters and send an error message, saying they are not allowed?

Finally only a comment about this implementation and the one in THAT PRODUCT:

- In THAT PRODUCT the filter can have multiple values, where each value selects generic library AND generic object AND generic member. The multiple values are OR'ed. This is great for a project, where the filter can select e.g. library ABC*, all source files, member DEF* combined with library QWE*, all sourcefiles, member RTY*.

- In our implementation we have one value, selecting generic library AND generic object AND generic member. This does not allow filtering only some members in library A and other members in library B.

To solve this, we would have to allow _a list_ of filter values (libraries, objects, objects types, member names and member types) and have the output be the combined selection of the filters in the list. How easy would that be? Not easy, I would guess - and this is NOT a challenge! 😉

2024-01-25 12:39 UTC, sebjulliand commented
@chrjorgensen I see your point. THAT PRODUCT let's you define filter strings, for members, and OR them.
In our case, we define one _filter string_ per filter.

I guess we could achieve the same result by associating multiple filters, as you said. We would need to list all the members from each filter and display them all at once (I just checked and THAT PRODUCT display them all at the same level).

We would need a different kind of filter; an association of filters, as you said. This should be done in a separate PR if we feel like it's needed. This one is already big enough 😄

2024-01-25 13:03 UTC, chrjorgensen commented
@sebjulliand 

> This should be done in a separate PR if we feel like it's needed. This one is already big enough 😄

I agree completely - I was just anticipating the reaction from our users who also have experience with THAT PRODUCT... 😆

2024-01-25 13:24 UTC, chrjorgensen commented
@sebjulliand I'm happy with this PR - you raise the bar once again! 😍 

🚀 🚀 🚀 🚀 🚀 🚀  - 6 out of 6! 😉 😆 

@worksofliam @Wright4i Please give this great PR a spin, so we can get it merged.

2024-01-25 16:03 UTC, worksofliam commented on src/testing/index.ts
> +  //FilterSuite
Accidently commit by the looks! I do this too when testing!!! Haha.

2024-01-29 15:34 UTC, worksofliam approved these changes
Code looks good, my user testing has been good, and the test cases are passing.

Thank you @sebjulliand!

2024-01-29 15:44 UTC, merged