This is for issue #1712
codefori/vscode-ibmi pull request #1807
Opened 2024-01-27 09:51 UTC by krethan

This is for issue #1712

Simplify the logic in the IBMi class by creating new IBMiSettings class.

2024-01-29 15:11 UTC, worksofliam commented
@krethan This is a nice change. I am going to work with the team to get a formal review ready - but in the meantime, I think the built-in formatter should be run over the `IBMiSettings.ts` file. You can open the command palette while inside that file, and search for 'Format Document'.

Thanks!

2024-01-30 05:21 UTC, krethan commented
@worksofliam Formatted IBMi.ts and IBMiSettings.ts

2024-02-02 06:04 UTC, krethan commented
@worksofliam Fixed merge issue in case it was preventing review.

2024-02-03 15:29 UTC, worksofliam commented
@krethan just wanted you to know that we are planning on taking a stab at reviewing this next week. We have been quite busy! Sorry about the wait.

2024-02-09 23:11 UTC, worksofliam requested changes
Generally on the right track. I've left some initial comments, but I believe there is likely a more to do outside of my review.

I don't know if the rest of @codefori/core agree with me, but ideally, I'd like to see this settings class not make use of the `vscode` namespace at all, and instead return the suffice information from each class method so the UI can be handled independently.

2024-02-09 23:11 UTC, worksofliam commented on src/api/IBMiSettings.ts
> +export default class IBMiSettings {
@sebjulliand and I were chatting about this class name and I think something more like `ConnectionSettings` or `InstanceSettings` might be more appropriate.

2024-02-09 23:11 UTC, worksofliam commented on src/api/IBMiSettings.ts
> +  constructor(connection: IBMi, progress: vscode.Progress<{ message?: string; increment?: number }>, connectionObject: ConnectionData, delayedOperations: Function[], reconnecting?: boolean) {
This constructor is likely too long considering most of the parameters end up as private member fields.

Please consider using `private connection: IBMi, private progress: ...`, etc, which then will mean you don't need to assign in the constructor or define them above the constructor.

2024-02-09 23:11 UTC, worksofliam commented on src/api/IBMiSettings.ts
> +  constructor(connection: IBMi, progress: vscode.Progress<{ message?: string; increment?: number }>, connectionObject: ConnectionData, delayedOperations: Function[], reconnecting?: boolean) {
More detail here: https://stackoverflow.com/a/48571668

2024-02-10 04:41 UTC, krethan commented on src/api/IBMiSettings.ts
> +export default class IBMiSettings {
@worksofliam I agree we should seperate the UI from this class. I will refactor the UI code back into the connection method of the IBMi class.

2024-02-10 04:42 UTC, krethan commented on src/api/IBMiSettings.ts
> +export default class IBMiSettings {
@worksofliam @sebjulliand I will go with ConnectionSettings for the class name

2024-02-13 04:40 UTC, krethan commented
@worksofliam I am about 75% through refactoring the ConnectionSettings.ts class now.

2024-02-16 07:30 UTC, krethan commented
@worksofliam Have couple introduced errors now. Working my way through them. Bug in home directory and another when asked to set bash to default, disconnect, connect again and still asking to set bash. Will ask for code review after these are fixed and committed.

2024-02-20 05:56 UTC, krethan commented
@worksofliam Okay ready for new review. I hope this one is good.

2024-02-28 19:10 UTC, worksofliam commented
@krethan As we get ready for the 2.8.0 release, is it possible you can fix the conflicts here? Thanks!

2024-03-01 17:50 UTC, worksofliam commented
@krethan It looks like the entire `out` directory has been committed. This likely shouldn't be the case. Any chance you can take a look at that?

2024-03-04 06:17 UTC, krethan commented
@worksofliam I reverted the commits back to remove everything in the out directory. Makes sense.

2024-03-05 15:33 UTC, worksofliam commented
@krethan We are so close! Please could you also fix the last remaining conflict?

Sorry this is taking a while. This is a very high impact PR so we are treading lightly right now.

2024-03-05 15:49 UTC, worksofliam requested changes
I have left you a review to get you started. There are lot of ends that need some cleaning up, espcially in regards to the use of `async` and `await`. I have high hopes for this PR, but it needs to be tight and tested before we can merge.

Other suggestions:

* Use the VS Code built-in formatter on `ConnectionSettings.ts`: F1 -> Format Document
* A few methods in `ConnectionSettings` use try catch, even though the calls inside of them do not crash - for example, `sendCommand` does not crash, but returns the exit code. It'd be nice to have those removed.
* A lot of the methods return `void`. It would be nice to make them more verbose, perhaps returning `boolean` or other in the future so we can write test cases for them.

2024-03-05 15:49 UTC, worksofliam commented on src/api/ConnectionSettings.ts
> +  private appendOutput(content: string) {
Looks like this method could be removed as it is unreferenced.

2024-03-05 15:49 UTC, worksofliam commented on src/api/ConnectionSettings.ts
> +  async deleteQCPTOIMPF(): Promise<CommandResult>{
This function is returning a function, which returns a Promise, so there is no need for the `async` keyword on the method here.

2024-03-05 15:49 UTC, worksofliam commented on src/api/ConnectionSettings.ts
> +  async deleteQCPFRMIMPF(): Promise<CommandResult> {
Same here with the `async` keyword.

2024-03-05 15:49 UTC, worksofliam commented on src/api/ConnectionSettings.ts
> +  async clearTempDataIFS() {
`async` keyword is not required as `await` is not being used in this method.

2024-03-05 15:49 UTC, worksofliam commented on src/api/ConnectionSettings.ts
> +  async clearTempDataSys(){
`async` keyword not required here either.

2024-03-05 15:49 UTC, worksofliam commented on src/api/IBMi.ts
> +        if (await connSettings.getTempLibrarySet() && this.config?.autoClearTempData) {
`await` not required here because `getTempLibrarySet` does not return a Promise.

2024-03-05 15:49 UTC, worksofliam commented on src/api/IBMi.ts
> +          if (await connSettings.checkQCPFRMIMPF) {
Brackets are missing from this method call.

2024-03-05 15:49 UTC, worksofliam commented on src/api/IBMi.ts
> +          const remoteApps = await connSettings.getRemoteApps();
`await` not required since `getRemoteApps` does not return a Promise.

2024-03-07 06:01 UTC, krethan commented on src/api/ConnectionSettings.ts
> +    let validLibs: string[] = [];
Removed.

2024-03-07 06:02 UTC, krethan commented on src/api/ConnectionSettings.ts
> +  private appendOutput(content: string) {
Method removed.

2024-03-07 06:05 UTC, krethan commented on src/api/ConnectionSettings.ts
> +  async deleteQCPTOIMPF(): Promise<CommandResult>{
removed Async.

2024-03-18 04:03 UTC, krethan commented
@worksofliam Should be good for review again.

2024-03-25 21:02 UTC, closed without merging