Stop letting the same document be opened twice
codefori/vscode-ibmi pull request #1837
Opened 2024-02-09 23:02 UTC by worksofliam

### Changes

* If you try and open a doucment, but already have it open in the oppisite edit mode, then you will get a warning and that open document will take focus.
* Clicking on an error should no longer open up a new document will try to use existing document URIs to inherit the readonly mode.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2024-02-09 23:14 UTC, chrjorgensen requested changes
@worksofliam Before testing, one question:

Some filesystems in IFS are case-sensitive, e.g. /QOpenSys... Isn't it a problem when you change the URI to lowercase?

Could we test for this before making the URI lowercase - or would it not work? I'm not that familiar with the URI in VS Code...

2024-02-09 23:17 UTC, worksofliam commented
@chrjorgensen 

I assume you're talking [about this line of code](https://github.com/codefori/vscode-ibmi/pull/1837/files#diff-dd1627a4d8b56dfba1fca9ceb939163f01edd1f2e5581d7ea33f6ef99d9e10ccR268) where we compare two URIs.

Yes, you're right. For IFS (`streamfile` internally) we should not be lowercasing the value. I am going to change this in a new commit.

2024-02-10 10:02 UTC, chrjorgensen requested changes
> For IFS (`streamfile` internally) we should not be lowercasing the value.

@worksofliam This was not quite what I meant - lowercasing IFS is fine, since most IFS filesystems are case-insensitive and `readme.md` is the same as `README.MD`. 

But `/QOpenSys` (and UDFS, which I think we can ignore) is case-sensitive, and `readme.md` is NOT the same as `README.MD`! So only IFS paths starting with '/QOpenSys' should be kept as-is and not be lowercased.

I'm after this since IBM YUM packages and other OSS tools are most often stored in `/QOpenSys`...

2024-02-14 16:45 UTC, worksofliam commented
@chrjorgensen I have applied the logic as you recommended. Take another look when you get a moment - thanks!!

2024-02-16 14:52 UTC, chrjorgensen requested changes
I ran the extension tests - and a lot of them failed (didn't on the master branch):

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/e7a4a9cc-1c6d-4917-aae8-9674a1a5f5e2)

???

2024-02-16 15:10 UTC, worksofliam commented
@chrjorgensen Fixed now.. give it another go

<img width="385" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/2f8c7c10-4d19-4790-9bbe-9f502b00f2a6">

2024-02-16 18:33 UTC, sebjulliand commented on src/api/Tools.ts
> +    const bathUriString = uriStringWithoutFragment(uri);
`bath`?! 😅
```suggestion
    const baseUriString = uriStringWithoutFragment(uri);
```

2024-02-16 19:07 UTC, sebjulliand requested changes
Looks good to me, save for that case-sensitivity issue and some very minor suggestions.
Otherwise, it works great and as expected. I'll approve after your final changes!

2024-02-16 19:07 UTC, sebjulliand commented on src/instantiate.ts
> +          vscode.window.showWarningMessage(`The file is already open in another mode.`);
Typo
```suggestion
          vscode.window.showWarningMessage(`The file is already opened in another mode.`);
```

2024-02-16 19:16 UTC, worksofliam commented
@sebjulliand Also added one more fix. Back to you for review!

2024-02-16 19:20 UTC, worksofliam commented
@sebjulliand Fixed a bug.. now it is ready!

2024-02-16 19:26 UTC, merged