Add option to show hidden files and directories in IFS browser
codefori/vscode-ibmi pull request #1839
Opened 2024-02-11 19:31 UTC by chrjorgensen

### Changes

Up until now the IFS browser shows all files and directories, even the hidden ones with a `.` in front of the name.
This PR will add an option to show or hide these files and directories in the IFS browser:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/8da9008f-055e-4052-b00a-909b7ac9c562)

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/236c1100-485d-4ad2-929c-470f203723ab)

The option can be changed in the connection settings:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/b0ca9066-bf1a-4320-a5a1-4947fbf525dc)

- it is on by default to show hidden files as before this change
- a keybinding Ctrl-H is added to toggle showing or hiding the hidden files and directories (the keybinding does not interfere with the Replace function in editors, which use the same key)
- special files and directories are always shown (see constant `ALWAYS_SHOW_FILES` in `ifsBrowser.ts`) to always show `.vscode` and `.gitignore`

### Checklist

* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2024-02-14 16:35 UTC, worksofliam commented
@chrjorgensen Any chance you can fix the conflict? 😬

2024-02-14 18:03 UTC, chrjorgensen commented
@worksofliam Conflict fixed...

2024-02-14 19:16 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +  return ALWAYS_SHOW_FILES.test(name);
One day, it'd be cool if this was grabbing from config instead of a constant - similar to `grepIgnoreDirs` - not needed for now.

2024-02-14 19:17 UTC, worksofliam commented
Initial reaction and usage of the code is awesome. I need to play with it more before I merge.

2024-02-15 10:26 UTC, chrjorgensen commented on src/views/ifsBrowser.ts
> +  return ALWAYS_SHOW_FILES.test(name);
I agree to some extent, thought about making a config value at first - but then, why have a config for that? The user can just show hidden files and directories, if they need to see them...

Can you think of any other files/directories, that should always be shown? The two in the constant were the ones I could think of...

2024-02-15 13:14 UTC, sebjulliand requested changes
Very good enhancement!
I have a few suggestions to make and a question:
- Shouldn't a button be added to the browser to toggle between hide/show hidden files? I'm quite sure users will either miss the feature of hit `ctrl+h` by mistake and ask why some files disappeared 😅

2024-02-15 13:14 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +          .filter(o => showHidden || !o.name.startsWith(`.`) || alwaysShow(o.name));
How about factorizing the filtering here?
```suggestion
    if (content) {
      try {
        const showHidden = instance.getConfig()?.showHiddenFiles;
        const filterIFSFile = (file:IFSFile, type: "directory" | "streamfile") => file.type === type && (showHidden || !file.name.startsWith(`.`) || alwaysShow(file.name));
        const objects = await content.getFileList(this.path, this.sort, handleFileListErrors);
        const directories = objects.filter(f => filterIFSFile(f, "directory"));
        const streamFiles = objects.filter(f => filterIFSFile(f, "streamfile"));
```

2024-02-15 13:14 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +          .addCheckbox(`showHiddenFiles`, `Show hidden files and directories in IFS browser.`, `When diabled, hidden files and directories (i.e. names starting with '.') will not be shown in the IFS
Small typo
```suggestion
          .addCheckbox(`showHiddenFiles`, `Show hidden files and directories in IFS browser.`, `When disabled, hidden files and directories (i.e. names starting with '.') will not be shown in the IFS browser, except for special config files.`, config.showHiddenFiles)
```

2024-02-15 14:19 UTC, worksofliam requested changes
I left some comments which I don't expect any changes for, because I love this feature! I have so many hidden folders I don't care about. But, do see Seb's comments for minor fixes and then assign a review back to me. Thanks!

2024-02-15 14:19 UTC, worksofliam commented on package.json
> +          "when": "code-for-ibmi:connected && view == ifsBrowser"
Is this `when` clause in the right place? Even if my focus on was on the IFS Browser, I couldn't get it to show up.

2024-02-15 14:19 UTC, worksofliam commented on package.json
> +        "when": "!editorFocus || editorReadonly"
This works, but Command+H on Mac is 'hide current window' :joy:

2024-02-15 14:19 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +  return ALWAYS_SHOW_FILES.test(name);
That makes complete sense!

2024-02-16 13:33 UTC, chrjorgensen commented on package.json
> +        "when": "!editorFocus || editorReadonly"
Any suggestion for another hot-key? I took the one from GNOME Nautilus, it was natural for me... 😉

2024-02-16 13:56 UTC, chrjorgensen commented on src/views/ifsBrowser.ts
> +          .filter(o => showHidden || !o.name.startsWith(`.`) || alwaysShow(o.name));
@sebjulliand Did your parents nick-name you "The Typescript Zip Master"?! 😆 

Suggestion committed... 👍

2024-02-16 14:16 UTC, chrjorgensen commented on package.json
> +          "when": "code-for-ibmi:connected && view == ifsBrowser"
I will remove the command and add an icon in the IFS browser instead.

2024-02-16 14:28 UTC, chrjorgensen commented on package.json
> +        "when": "!editorFocus || editorReadonly"
I removed the hotkey - the user can add it to the settings if needed.

2024-02-16 14:42 UTC, chrjorgensen commented
@worksofliam The keybinding has been removed and replaced by an icon in the IFS browser navigation menu, as suggested by @sebjulliand 

Feel free to test and merged, if approved. 🙏

2024-02-16 15:21 UTC, worksofliam approved these changes
@chrjorgensen Thanks for taking my shortcut consideration into account! I prefer the icon over the shortcut for sure due to it already being used on Mac.

Works good to me. Thanks!

2024-02-16 15:21 UTC, merged