Connection browser enhancements
codefori/vscode-ibmi pull request #1845
Opened 2024-02-14 23:35 UTC by chrjorgensen

### Changes

This PR adds some enhancements to the server browser:
- add a sort connection option 

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/9b8ccc3e-a080-476e-9cc9-4735f9256f1f)

- add Rename Connection menu item

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/8ddda05d-94b0-445b-a865-20842be10081)

- remove most connection commands from command palette
- only show Connection Settings in command palette when connected
- remove cached server settings when option is changed to disable

### Checklist

* [x] have tested my change
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining

2024-02-14 23:42 UTC, chrjorgensen commented on src/locale/ids/fr.ts
> +  'connectionBrowser.renameConnection.prompt': `Rename connection {0}`,
@sebjulliand Could I ask you to translate these three new texts into French? :pray:

2024-02-15 14:28 UTC, worksofliam commented
Not part of my review but an issue nonetheless:

If I rename a connection, enter a new name, and get this error:

<img width="492" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/06d9e614-b08d-4cb0-8f6d-d0a4e79ea30f">

But then if I refresh the view, the name is updated correctly.

2024-02-16 12:26 UTC, chrjorgensen commented
@worksofliam Could your error be caused by some "molested" configuration settings in VS Code, where the `name` attribute is not there as expected?

I've seen many examples of this in my own settings - like the `"button" = "save"`example, which is also seen in other users settings in some of the issues...

A connection has values in up to four different places in the settings / storage, and currently there is a danger in the code, that only part of them gets the new name for the connection. So be careful when testing - do not test on important connections!

I will add a try-catch block to catch any errors and not update anything if errors occurred - stay tuned...

2024-02-16 13:25 UTC, chrjorgensen commented
@worksofliam Error handling has been added and you should get more error information - and not get any connection changed if error occurred. (Tested this with `settings.json` opened - cool to see the file being updated by the rename command!)

@sebjulliand Now even more messages to translate to French... 😉

2024-02-17 15:25 UTC, sebjulliand requested changes
Looks good and works fine so far! Thank you!
Just some very minor style change were requested, but that's just me being me.

2024-02-17 15:25 UTC, sebjulliand commented on src/views/ConnectionBrowser.ts
> +              GlobalStorage.get().deleteServerSettingsCache(server.name);
Indentation
```suggestion
                GlobalStorage.get().setServerSettingsCache(newName, cachedConnectionSettings);
                GlobalStorage.get().deleteServerSettingsCache(server.name);
```

2024-02-17 15:25 UTC, sebjulliand commented on src/views/ConnectionBrowser.ts
> +        let connections = GlobalConfiguration.get<ConnectionData[]>(`connections`) || [];
Use `const` whenever you can
```suggestion
        const connections = GlobalConfiguration.get<ConnectionData[]>(`connections`) || [];
```

2024-02-17 15:55 UTC, chrjorgensen commented on src/views/ConnectionBrowser.ts
> +        let connections = GlobalConfiguration.get<ConnectionData[]>(`connections`) || [];
Agreed - just me getting confused that you can change a `const`... :roll_eyes:

2024-02-17 16:45 UTC, sebjulliand commented on src/views/ConnectionBrowser.ts
> +        let connections = GlobalConfiguration.get<ConnectionData[]>(`connections`) || [];
The object state can change and that's fine.It's reference cannot, giving you the assurance that you'll always manipulate the same object and it won't be replaced somehow.

2024-02-17 16:46 UTC, sebjulliand approved these changes
Brilliant! Let's merge!

2024-02-17 16:46 UTC, merged