Trim whitespaces in object filter's library and object field
codefori/vscode-ibmi pull request #1848
Opened 2024-02-16 21:53 UTC by sebjulliand

### Changes
Fixes https://github.com/codefori/vscode-ibmi/issues/1847

Whitespaces in object filter's `library` and `object` fields were not trimmed, resulting in the filtering not working correctly.

### Checklist
* [x] have tested my change

2024-02-16 22:36 UTC, chrjorgensen requested changes
@sebjulliand Code looks good to me - only one question... 😉

2024-02-16 22:36 UTC, chrjorgensen commented on src/webviews/filters/index.ts
> +              .map(o => useRegexFilters ? o : o.toLocaleUpperCase().trim())
@sebjulliand Why trimming filters when saving the filter? The filter works great with or without blanks in-between, and not trimming the filters allows the user to space the filter out for better readability...

2024-02-16 22:51 UTC, chrjorgensen commented on src/webviews/filters/index.ts
> +              .map(o => useRegexFilters ? o : o.toLocaleUpperCase().trim())
Maybe just trimming before splitting would be sufficient - then the user can have spaces in-between, and the filter would still be left-justified without trailing spaces.

2024-02-17 00:07 UTC, worksofliam commented
Can we get a test case for this? :)

2024-02-17 09:58 UTC, sebjulliand commented on src/webviews/filters/index.ts
> +              .map(o => useRegexFilters ? o : o.toLocaleUpperCase().trim())
That may indeed be better! Thanks Christian!

2024-02-17 10:09 UTC, sebjulliand commented
@chrjorgensen filters are not trimmed on saving anymore
@worksofliam I added a test for filters with whitespaces

2024-02-17 10:33 UTC, chrjorgensen approved these changes
@sebjulliand You rock :rocket: :+1: - and work in the weekend! :-1: :wink: 

But so do I, so it's okay... :laughing: 

Approved and merged. We should think of making a prerelease for users to avoid this error...

2024-02-17 10:34 UTC, merged