Add support for delete hotkey in browsers
codefori/vscode-ibmi pull request #1849
Opened 2024-02-17 20:30 UTC by sebjulliand

### Changes
This PR adds support for pressing the delete key to delete selected items in the Connection, IFS and Object browser.
It also restore the possibility to delete source files (this was lost with the filter enhancement).

All delete confirmation dialogs are now modals.

### Checklist
* [x] have tested my change

2024-02-18 00:13 UTC, chrjorgensen requested changes
@sebjulliand Nice enhancement! :+1: 

A quick test seems to show some navigation issues:

- In Connection Browser (CB) and Object Browser (OB), when an item is marked and the cursor moved to another item, it's not the item marked by the cursor that will be deleted, but the item selected (filled background). This can be confusing for the user (me!).
- Delete connection confirmation dialog is not modal, but still a warning message.
- In the OB `Delete` does not work if no object is selected. I would expect the object marked by the cursor to be deleted when pressing `Delete`.
- How do I select a member in OB without it being opened?
- It's not possible to mark objects in OB as in IO - not enabled for OB, since there are no drag'n'drop?
- Pressing `Delete` in IO without marking any files shows the following error:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/d18e56bb-46db-4a1e-a220-838d4dfa46ed)


I hope the navigation issues can be fixed by having `Space` mark an item and `Enter` open the marked item(s). It's not that intuitive to have to hold `Shift` and press `Up` or `Down` to mark one or more items in the lists... But maybe it's not possible in the current API's? :pray:

2024-02-18 00:17 UTC, chrjorgensen commented
@worksofliam I'm looking forward to your review - I think we all should have a try with this PR, since it's about deleting objects and we should reduce the risk of users deleting something by mistake... :pray: 
@Wright4i Your opinion is also welcome, of course! :heart:

2024-02-18 09:13 UTC, chrjorgensen commented
Some additional thoughts:

- maybe we should have all views working like the IFS browser, i.e. allowing multiple selections (drag'n'drop may be overkill, but could be used for re-arranging the order of the items)?
- It should be clear to the user what is going to be deleted when `Del` is pressed. If not possible to make completely clear, then maybe remove the `Del`hotkey and have the user right-click instead?

I like the way the delete operation has been changed in the code. So maybe we at least should use that change?

FInally, is it just me or **does Code for IBM i start faster now, with the new initialization of the Connection Browser?** :+1:

2024-02-18 10:10 UTC, sebjulliand commented
Thank you @chrjorgensen , on point as usual!
I fixed the few issues you found I could work on. The rest (mostly the selection bits) is in the hand of the API and I have no way of working around that, which makes the delete key support questionable. I agree the other enhancement should be kept. The hotkey is up to debate 😁 Multi-selection/drag and drop should also be considered.

2024-02-18 10:16 UTC, chrjorgensen commented
Agree - let's see what the other team members @worksofliam and @Wright4i have to say...

2024-02-21 15:16 UTC, worksofliam requested changes
Nice PR. Love the UX feature. It might be easier for me to go through and delete all my testing connections now - thanks!

Just some thoughts:

* How do you use the delete key to delete a connection? When you highlight/select a connection, you connect right away.
* You can also apply that logic to the IFS Browser and Object Browser. You can use the delete key without clicking it first (which tends to expand or connect) - though it is still useful.

edit: i realize this is what you and @chrjorgensen were already discussing! Perhaps for the connection, we require them click on the connection button, though this is a huge UX change and likely not to be appreciated by many. But in general, I say key the functionality for IFS Browser and Object Browser.

2024-02-21 15:16 UTC, worksofliam commented on src/views/ifsBrowser.ts
> +                    const removeResult = await connection.sendCommand({ command: `rm -rf ${Tools.escapePath(item.path)}` })
I may come back to this later on. Ideally we wouldn't be looping through each chosen file to delete, we'd just build up a single command to delete all chosen files: `rm -rf a b c` instead of `rm -rf a`, `rm -rf b`, etc. I know it has been like this for a while.

2024-02-21 15:16 UTC, worksofliam commented on src/views/objectBrowser.ts
> +        // TODO: Progress message about deleting!
This to do can be removed!

2024-02-21 15:16 UTC, worksofliam commented on src/views/objectBrowser.ts
> +        const deleteResult = await connection.runCommand({
Long term goal, not required here: get this `DLTOBJ` into an API. We have `checkObject`, why not `deleteObject`?

2024-02-24 11:34 UTC, chrjorgensen requested changes
@sebjulliand Could you add the number of elements to the confirmation messages - like it is in the IFS browser? I think that is an extra assurance for the user to see the number of elements that will be deleted - if 3 was supposed to be selected and 4 is mentioned in the message, this is a quick alert.

2024-02-25 13:41 UTC, sebjulliand commented
> @sebjulliand Could you add the number of elements to the confirmation messages - like it is in the IFS browser? I think that is an extra assurance for the user to see the number of elements that will be deleted - if 3 was supposed to be selected and 4 is mentioned in the message, this is a quick alert.

There you go!

2024-02-25 22:38 UTC, chrjorgensen requested changes
@sebjulliand This error is occurring when I start debugging:

```
[{
	"resource": "/d:/Data/Develop/code-for-ibmi/src/views/objectBrowser.ts",
	"owner": "typescript",
	"code": "2663",
	"severity": 8,
	"message": "Cannot find name 'isProtected'. Did you mean the instance member 'this.isProtected'?",
	"source": "ts",
	"startLineNumber": 324,
	"startColumn": 105,
	"endLineNumber": 324,
	"endColumn": 116
}]
```

Maybe your branch was not updated to latest master?

2024-02-26 14:08 UTC, chrjorgensen commented
@sebjulliand Something's wrong with the current state - when I check out your feature branch, I get the following error:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/73786fa2-f08e-419c-9cf2-1b420cff4e4f)

Could you fix the merge conflict present and force-push your local branch (having no errors!)?
Would be nice to complete this great change asap. 😍

2024-02-26 15:34 UTC, sebjulliand commented
@chrjorgensen I had to nuke the branch and make everything clean, so I had to force-push a clean state, hence Git being confused.
I fixed the conflict so now it should be OK - pulling the changes shouldn't show any error. And hopefully it still works 🤣

2024-02-26 22:13 UTC, worksofliam requested changes
**Bug**: I am getting this message when expanding an `*ALL` object filter - but worked fine with `*SRCPF`:

<img width="474" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/d38be868-be64-4622-8101-ea4fb4c6a2b9">

Deleting multiple connections works like a charm:

![image](https://github.com/codefori/vscode-ibmi/assets/3708366/955f0227-d439-4e47-8ea1-eeb0dbb49002)

Deleting multiple directories works, but I think a progress indicator would be nice instead of messages for each chosen path, and then perhaps a final message saying they have been deleted. Not a requirement but nice for the user.

![image](https://github.com/codefori/vscode-ibmi/assets/3708366/63c5559a-ef8d-4c34-b01b-84af71e98ea7)

Deleting filters worked good:

<img width="907" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/df6c5a65-e75b-408a-bb4e-a370ea26abe1">

2024-02-27 09:12 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +                    const removeResult = await connection.sendCommand({ command: `rm -rf ${Tools.escapePath(item.path)}` })
Done! 😁

2024-02-27 09:16 UTC, sebjulliand commented
Thanks for the testing guys.
@worksofliam I fixed my stupid mistake. I also went the extra mile and optimized the delete process for the IFS files:
- The selection is first reduced to keep only folders and files whose parent folders are not in the selection
- We build a single `rm -rf` command for what remains after the reduction
- The command is run with a progress notification

It goes faster than running rm for each element, that goes without saying 😋

@chrjorgensen I'll need once again a small translation 🙏🏻

2024-02-27 15:29 UTC, worksofliam approved these changes
It liked me deleting an object and filter at the same time - nice!

<img width="886" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/7ab11b88-1cf7-4f53-baa2-31816e52fe47">

And worked with the IFS Browser!

<img width="858" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/5cc8c584-22f4-463e-8833-a1cf17412b04">

Plus - the progress bars are working as expected!

2024-02-27 15:56 UTC, chrjorgensen requested changes
@sebjulliand Works great! 😍 

Only one issue found: Deleting members shows this confirmation message - with a `()`?

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/32db875e-cc81-463e-9b18-811225ae0c7f)

2024-02-27 16:31 UTC, chrjorgensen commented
> > @sebjulliand Works great! 😍
> > Only one issue found: Deleting members shows this confirmation message - with a `()`?
> > ![image](https://private-user-images.githubusercontent.com/13275072/308245643-32db875e-cc81-463e-9b18-811225ae0c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTAxNTksIm5iZiI6MTcwOTA0OTg1OSwicGF0aCI6Ii8xMzI3NTA3Mi8zMDgyNDU2NDMtMzJkYjg3NWUtY2M4MS00NjNlLTliMTgtODExMjI1YWUwYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE2MDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZjAwNmZjN2Q0NDBhYmMxZDIxYjdlMTc4NzAwYmQzYmQzMTJjMjBiNDY3OTRhYmM5YTA3NjhjNzM1NDVlOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sj7AssL1QgOCNDaWL7xnXqf6tpU65TTcB1hSbL6PvMk)
> 
> This is supposed to be the member's extension between `()`! Does your member has no extension?!

No, no extension... but I think it is quite inconsistent to present a member as `LIB/FILE/MEMBER (EXT)`, when we in all other places write `LIB/FILE/MEMBER.EXT`. WDYT? Would it be much work to present members like in all other places?

2024-02-27 16:56 UTC, chrjorgensen commented
I made a silly - but valid - test, deleting 500 members in a source file... and found two issues:

1. The confirmation dialog filled the screen from top to bottom, with a slider. Is it possible to have a max height of the window?
2. The progress during deletion does not move - only the member name is rolling... Could it be the number to be deleted, that makes no progress move?

Sorry for being a PIA! 😢

2024-02-27 18:08 UTC, sebjulliand commented
> I made a silly - but valid - test, deleting 500 members in a source file... and found two issues:
> 
>     1. The confirmation dialog filled the screen from top to bottom, with a slider. Is it possible to have a max height of the window?
> 
>     2. The progress during deletion does not move - only the member name is rolling... Could it be the number to be deleted, that makes no progress move?
> 
> 
> Sorry for being a PIA! 😢

1. We have no control over the dialogs' size. Either we keep it like that, or I can limit the number items listed and print "XX more..." if the list length goes beyond that limit.
2. I' look into that.

2024-02-27 19:05 UTC, chrjorgensen commented on src/views/objectBrowser.ts
> +    return this.path;
How about this?

```suggestion
    return `${this.path}.{this.member.extension}`;
```

2024-02-27 19:12 UTC, sebjulliand commented on src/views/objectBrowser.ts
> +    return this.path;
No, I tried that but the `path` already contains the extension! 😉
This is how it looks right now:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/800d58d7-1ea3-4fc6-aab4-baa4f7f3cfe6)

2024-02-27 19:18 UTC, chrjorgensen commented on src/views/objectBrowser.ts
> +    return this.path;
My mistake - tested with a member without extension again... 😄

2024-02-27 21:08 UTC, sebjulliand commented
@chrjorgensen : I fixed the progress stuck at 0 (rounding made the increment equals to 0...that was silly of me as the progress supports non-integer increments).
It should be OK now!

2024-02-27 21:20 UTC, chrjorgensen approved these changes

2024-02-27 21:21 UTC, chrjorgensen commented
@sebjulliand Looking good to me - merge at will. 😍

2024-02-27 21:23 UTC, merged