Add tooltip for source files showing member count, source length and CCSID
codefori/vscode-ibmi pull request #1850
Opened 2024-02-18 00:34 UTC by chrjorgensen

### Changes

This PR will add a tooltip on source files in the Object Browser. The tooltip contains
- object description
- member count
- source length
- CCSID

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/bca9fdb3-2da9-4935-8b66-fafa011b1db0)

### Checklist

* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2024-02-18 09:03 UTC, chrjorgensen commented
All tooltip texts has been changed, so the text with tabs are combined and the tooltip value is a value in the text.
This allows for individual formatting between languages and gives a cleaner look..

2024-02-18 10:22 UTC, chrjorgensen commented
@sebjulliand There are some new texts for the source file tooltips - could you... 😉

2024-02-18 10:32 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'objectBrowser.sourceFile.tooltip.CCSID': 'CCSID:\t\t{0}',
📖
```suggestion
  'objectBrowser.sourceFile.tooltip.text':'Texte:\t\t{0}',
  'objectBrowser.sourceFile.tooltip.members': 'Membres:\t{0}',
  'objectBrowser.sourceFile.tooltip.length': 'Longueur:\t{0}',
```

2024-02-18 10:34 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'ifsBrowser.file.tooltip.size': `Taille:\t\t\t{0}`,
Remove a tab to align
```suggestion
  'ifsBrowser.file.tooltip.size': `Taille:\t\t{0}`,
```

2024-02-18 10:36 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'objectBrowser.member.tooltip.lines': 'Lignes:\t\t\t{0}',
Fixed alignment
```suggestion
  'objectBrowser.member.tooltip.lines': 'Lignes:\t\t{0}',
```

2024-02-18 10:42 UTC, sebjulliand requested changes
Very nice! You can never get enough information 😄
Find the missing FR translations and fixes in the suggestions. Then it's a merge!

2024-02-18 10:42 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'objectBrowser.sourceFile.tooltip.length': 'Length:\t\t{0}',
📖
```suggestion
  'objectBrowser.sourceFile.tooltip.text':'Texte:\t\t{0}',
  'objectBrowser.sourceFile.tooltip.members': 'Membres:\t{0}',
  'objectBrowser.sourceFile.tooltip.length': 'Longueur:\t{0}',
```

2024-02-18 10:50 UTC, chrjorgensen commented
@sebjulliand Thanks - and the CCSID was for you! 😘😂

2024-02-18 11:20 UTC, chrjorgensen commented on src/locale/ids/fr.ts
> +  'ifsBrowser.file.tooltip.size': `Taille:\t\t\t{0}`,
The current number of tabs makes the columns align - because the text length is different:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/5904b0aa-6316-4b61-ae01-dafab653bf5c)

Is that not what you get in your instance of VS Code?

2024-02-18 11:25 UTC, chrjorgensen commented on src/locale/ids/fr.ts
> +  'objectBrowser.member.tooltip.lines': 'Lignes:\t\t\t{0}',
Same as above - number of tabs should be different between the tooltip lines:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/1a08bc57-0e04-44fe-846e-61947bae901c)

2024-02-18 11:26 UTC, chrjorgensen commented
@sebjulliand PR is ready for final review - and merge, if approved... :pray:

2024-02-18 11:39 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'ifsBrowser.file.tooltip.size': `Taille:\t\t\t{0}`,
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/03ba7787-6013-4066-9ba5-39d2d49c6b90)
Sad, right? 😅

2024-02-18 11:39 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'objectBrowser.member.tooltip.lines': 'Lignes:\t\t\t{0}',
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/3fb5b9d9-7097-4b35-a06d-d75b92d968b4)

2024-02-18 11:42 UTC, sebjulliand approved these changes
Good!
As for the alignment being different between you and me, that may be related to our display configuration. There may not be much we can do about it 🙄 So feel free to merge whenever you want.

2024-02-19 22:26 UTC, chrjorgensen commented
@sebjulliand The alignment in the tooltips for sourcefiles and members has been fixed - by changing the tooltip into a HTML table!

Actually didn't know it was possible until I found this: 
https://github.com/microsoft/vscode/blob/6d2920473c6f13759c978dd89104c4270a83422d/src/vs/base/browser/markdownRenderer.ts#L296

💣

2024-02-19 23:07 UTC, chrjorgensen commented
@sebjulliand @worksofliam Sorry, I went berserk in tooltips! 😆

2024-02-20 13:05 UTC, sebjulliand requested changes
It looks good, no question asked!
But having the formatting in the translations looks a bit wrong 😅
It would be better, IMHO, to have a tool function that generates a simple table for you and reuse it where you need the tooltips.

Something along these lines:
```typescript
export function generateTooltipTable(header:string, rows: Record<string, any>){
  return /* html */ `<table>
      <thead>${header}</thead>
      ${Object.entries(rows).map(([key, value]) => `<tr><td>${t(key)}</td><td>${value}</td></tr>`)}      
    <table>`;
  }
```

Used like that:
```typescript
this.tooltip = new vscode.MarkdownString(Tools.generateTooltipTable(this.path, {
  text:sourceFile.text,
  members:sourceFile.memberCount,
  length:sourceFile.sourceLength,
  CCSID: sourceFile.CCSID
}));
```

Yes, the translation keys (text, member, length...) are not tied to a specific domain in this case, but it may be something we should think about too, having generic translations.

What do you think?

2024-02-20 13:22 UTC, chrjorgensen commented
@sebjulliand I agree - will make the necessary changes in a new commit...

The translation keys were actually generic before my changes - so they will go back to become that.

This has been a bit trial-and-error and going back-and-forth... I should probably squash the commits and force-push the final commits. Right?

2024-02-20 13:45 UTC, sebjulliand commented
@chrjorgensen Trying to hide your mess under the carpet I see, hmm? 😁
Just kidding, squash and force push as you please; make it clean!

2024-02-20 16:59 UTC, chrjorgensen commented
@sebjulliand Cleaned up my mess - don't look under the carpet! 😄 

Final review - then we can hopefully merge... 😍

2024-02-21 08:34 UTC, merged