Ignore error copying empty member
codefori/vscode-ibmi pull request #1851
Opened 2024-02-18 12:21 UTC by chrjorgensen

### Changes

This PR will fix the error occurring, when copying an empty member.

Currently the copy ends with the following errors:

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/c1a3b7ad-e831-49bd-b9f5-2b0e7bc3c80c)

and the member list is not updated, even though the new member is created (as empty).

The PR changes the code to only report errors if CPF2869 (Empty member &3 in file &1 in library &2 is not copied) is not among the errors. So now copying an empty member will act exactly like copy members with lines.

### Checklist

* [x] have tested my change

2024-02-18 12:24 UTC, chrjorgensen commented
@sebjulliand I added a property `length` to `IBMiMessages` - will it cause any conflicts in other places parsing messages from stderr? I haven't seen any in my tests, but just want to be share (always anxious when changing types... :laughing:)

2024-02-20 13:40 UTC, sebjulliand requested changes
The change works fine, thanks for that!
See my comment about `length`. It's harmless to add it, but is it useful?

2024-02-20 13:40 UTC, sebjulliand commented on src/api/Tools.ts
> +      length: messages.length
Why bother with an extra `length` field when we already expose `messages`? We can simply call `messages.length`.

2024-02-20 13:40 UTC, sebjulliand commented on src/views/objectBrowser.ts
> +            if (messages.length && !messages.findId(`CPF2869`)) {
Following up with the above comment, we can simply access the length `property` from `messages`.
```suggestion
            if (messages.messages.length && !messages.findId(`CPF2869`)) {
```

2024-02-20 22:21 UTC, chrjorgensen commented on src/api/Tools.ts
> +      length: messages.length
See reply in other comment...

2024-02-20 22:23 UTC, chrjorgensen commented on src/views/objectBrowser.ts
> +            if (messages.length && !messages.findId(`CPF2869`)) {
My lack of knowledge... couldn't make `.length` work, because I didn't duplicate `messages.`...

Of course you're right - I'll fix it.

2024-02-21 08:36 UTC, sebjulliand approved these changes
Perfect 🥰

2024-02-21 08:36 UTC, merged