Allow dragging members to IFS directories
codefori/vscode-ibmi pull request #1857
Opened 2024-02-20 12:14 UTC by chrjorgensen

### Changes

This PR will allow dragging members from the Object browser into IFS directories in the IFS browser, to allow easy conversion of source members to streamfiles.

When the member is dropped into the directory, it will be copied using the CPYTOSTMF command. The streamfile will be named the member including extension in lowercase, and it will be UTF-8 encoded.

### Checklist

* [x] have tested my change
* [x] **for feature PRs**: PR only includes one feature enhancement.

2024-02-20 14:38 UTC, sebjulliand requested changes
There you go @chrjorgensen .
You were very close to achieve it! You don't need to bother with the `BrowserItem` type since you sends a list of URI in your data transfer.
Then you only need to split your data, parse them back to URI and feed the to the `parseMember` tool function. Then use `Tools.qualifyPath` to get an IFS path and you're good to go!

2024-02-20 14:38 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +import { BrowserItem, BrowserItemParameters, CommandResult, FocusOptions, IFSFile, IFS_BROWSER_MIMETYPE, ObjectBrowserMemberItem, OBJECT_BROWSER_MIMETYPE, WithPath } from "../typings";
```suggestion
import { BrowserItem, BrowserItemParameters, CommandResult, FocusOptions, IFSFile, IFS_BROWSER_MIMETYPE, OBJECT_BROWSER_MIMETYPE, WithPath } from "../typings";
```

2024-02-20 14:38 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +        console.log(command);
```suggestion
  private async moveOrCopyMembers(memberURIs: vscode.Uri[], toDirectory: IFSDirectoryItem) {
    const connection = instance.getConnection();    
    if (connection && memberURIs.length) {
      let result: CommandResult;
      memberURIs.forEach(memberURI => {
        const member = connection.parserMemberPath(memberURI.path);
        const command: string = `CPYTOSTMF FROMMBR('${Tools.qualifyPath(member.library, member.file, member.name, member.asp)}') TOSTMF('${toDirectory.path}/${member.basename}') STMFCCSID(1208) ENDLINFMT(*LF)`;
        console.log(command);
```

2024-02-20 22:11 UTC, chrjorgensen commented
@sebjulliand Thank you for helping out - couldn't have done it without you, however close I were. I'm so grateful. 🥇 

The PR description has been changed and is no longer a draft.

2024-02-21 08:48 UTC, sebjulliand commented on src/locale/ids/fr.ts
> +  'ifsBrowser.copyToStreamfile.failed': `Error copying member(s) to {0}: {1}`,
Vive la France!
```suggestion
  'ifsBrowser.copyToStreamfile.infoMessage': `{0} membre(s) copiés en fichier(s) stream dans {1}.`,
  'ifsBrowser.copyToStreamfile.failed': `Erreur lors de la copie des membres vers {0}: {1}`,
```

2024-02-21 08:50 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +          this.CopyMembers(memberUris, toDirectory)
```suggestion
          this.copyMembers(memberUris, toDirectory)
```

2024-02-21 08:50 UTC, sebjulliand commented on src/views/ifsBrowser.ts
> +  private async CopyMembers(memberUris: vscode.Uri[], toDirectory: IFSDirectoryItem) {
```suggestion
  private async copyMembers(memberUris: vscode.Uri[], toDirectory: IFSDirectoryItem) {
```

2024-02-21 08:53 UTC, sebjulliand requested changes
Neat! That is a very nice addition 😍
Just watch out for the case of your function. Fix that and we'll be good for a merge!

2024-02-22 08:18 UTC, chrjorgensen commented
@sebjulliand Done - approve? 😃

2024-02-22 09:32 UTC, sebjulliand approved these changes
@chrjorgensen approved & merged! Good job! 👍🏻

2024-02-22 09:32 UTC, merged