Speed up logic to validate member exists
codefori/vscode-ibmi pull request #1867
Opened 2024-02-22 23:55 UTC by chrjorgensen

### Changes

This PR is an alternative to PR #1826 and will keep the check for member existence.

Instead of using QSYS2.SYSPARTITIONSTAT to retrieve the member information, which could be slow on small server with many, many members, the code introduces a new SQL table function <tempLib>.GETMBRINFO to get the information for the specific member. API QUSRMBRD is used by GETMBRINFO behind the scenes.

### Checklist

* [x] have tested my change

2024-02-23 14:36 UTC, worksofliam requested changes
Looks okay. Initial glance is that it will continue to ask about installation since you don't update the settings cache for the connection. I do this in #1866 with a new API. Maybe that needs to be reviewed/merged first so you can use that API here?

2024-02-23 14:36 UTC, worksofliam commented on src/languages/sql/getmbrinfo.ts
> +          connection.remoteFeatures[`GETMBRINFO.SQL`] = `${config.tempLibrary}.GETMBRINFO`;
Similar to what I have done in #1866. you will need to store into the cache that this has been installed otherwise you will keep getting the popup:

https://github.com/codefori/vscode-ibmi/pull/1866/files#diff-3c2633023201c776a18178afef7bde70914ff9c816de4afe480dc2c920af3211R52

2024-03-05 15:09 UTC, worksofliam commented on src/api/IBMiContent.ts
> +  async getMemberInfo(library: string, sourceFile: string, member: string): Promise<IBMiMember | undefined> {
I think throwing `undefined` if the member does not exist makes sense. But, I think this API should throw an error if the feature (`GETMBRINFO.SQL`) is not installed.

2024-03-05 15:09 UTC, worksofliam commented on src/instantiate.ts
> +                const memberInfo = await content!.getMemberInfo(lib, file, member.name);
Handle if `getMemberInfo` ends with a crash.

2024-03-05 15:13 UTC, worksofliam requested changes
It works very well. You are right, the performance is so amazing. Couple of things:

1. The SQL function is being created every time I connect to a system. Similar to CL, we need to store that we are installing it after it is installed.
2. We need to handle it better if the installation failed at runtime. Returning the member, undefined or crashed to represent the different states would be good in my opinion.

2024-04-02 18:59 UTC, worksofliam commented
@sebjulliand I have requested your review here will Christian is away. No rush whatsoever.

2024-04-12 07:57 UTC, chrjorgensen commented
@sebjulliand Seems like you and @Wright4i are the only ones left, who hasn't made commits and can review...? 😉

2024-04-18 19:05 UTC, chrjorgensen commented
@Wright4i @sebjulliand Merge conflicts have been resolved - ready for review...

2024-04-18 19:35 UTC, worksofliam commented
@chrjorgensen I am going to give this another review today and I will approve and merge if acceptable. Thanks!

2024-04-18 20:05 UTC, worksofliam approved these changes
@chrjorgensen Great works. Made one more commit to cleanup unused variables and added some small comments. Let's go!

2024-04-18 20:05 UTC, merged