Changes/debugger_certs
codefori/vscode-ibmi pull request #1895
Opened 2024-02-29 21:40 UTC by worksofliam

### Changes

High level API:

* Adds new `usingBash` method to the `IBMi` class

Debug specific:

* [x] Changes default location for debugger certificates out of ProdData
* [x] Logic written to support uses who are already using the legacy debug certificate directory (inside ProdData)
* [x] Require bash setup before generating certificates
* [x] No longer use a CA when generating certificates
* [x] Documentation PR created and attached to this PR: https://github.com/codefori/docs/pull/27

The walkthroughs need to be updated too, but that will be done in another PR after this as we plan on migrating all walkthroughs to this extension.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2024-03-06 20:35 UTC, sebjulliand commented on src/api/debug/certificates.ts
>      `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`
A couple of suggestions here:
- Removed a seemingly redundant -sha256 flag
- Delete unused file when the pfx is generated; looks like only the pfx is required to run the service. I removed them manually and it was ok.
- Give read-only access to everyone (better than trusting the default access, which may depend on an unexpected `umask`)
```suggestion
    `openssl genrsa -out debug_service.key 2048`,
    `openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=${host}'`,
    `openssl x509 -req -in debug_service.csr -signkey debug_service.key -out debug_service.crt -days 1095 -sha256 -req -extfile <(printf "${extFileContent}")`,
    `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`,
    `rm debug_service.key debug_service.csr debug_service.crt`,
    `chmod 444 debug_service.pfx`
```

2024-03-06 20:38 UTC, sebjulliand requested changes
It works as expected. I changed the certificate location, and I could still debug.
Just a suggestion to think about and we'll be good to go!

2024-03-06 20:38 UTC, sebjulliand commented on src/api/debug/certificates.ts
> +    `openssl x509 -req -in debug_service.csr -signkey debug_service.key -out debug_service.crt -days 1095 -sha256 -sha256 -req -extfile <(printf "${extFileContent}")`,
Why an arbitrary 1095 days here?

2024-03-07 15:16 UTC, sebjulliand commented on src/api/debug/certificates.ts
>      `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`
Better idea: remove the `crt` file and get the certificate from the service itself, so you're guaranteed to get the right client certificate.

Get the output from this when the service runs (here on port 8005):
```bash
openssl s_client -connect localhost:8005 -showcerts < /dev/null 2> /dev/null | openssl x509 -outform PEM
```

2024-03-07 15:27 UTC, worksofliam commented on src/api/debug/certificates.ts
>      `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`
Can you make an issue for that idea itself?

2024-03-07 15:29 UTC, sebjulliand commented on src/api/debug/certificates.ts
>      `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`
I can even PR the hell out of it if you want.

2024-03-07 15:31 UTC, sebjulliand commented on src/api/debug/certificates.ts
>      `openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:${host}`
Hold my tea...

2024-03-17 18:01 UTC, sebjulliand approved these changes
@worksofliam looks good to me.
I pushed a commit to clean up the code a bit and also make it clear that there is a service certificate and a client certificate. I also made sure only a PFX file can be selected when importing a service certificate (even though that feature would require more work).

Anyway, have a look and merge when you're comfortable.

2024-03-18 14:25 UTC, merged