'Add to library list' and 'Set as current library' actions on browsers items
codefori/vscode-ibmi pull request #1905
Opened 2024-03-03 16:47 UTC by sebjulliand

### Changes
This PR adds a new `Set as current library` action, available from:
- Libraries in the `User Library List` view
- Filters and .lib objects from the `Object Browser`

It also adds the `Add to library list` action on:
- Filters and .lib objects from the `Object Browser`

![image](https://github.com/codefori/vscode-ibmi/assets/11096890/fa9521c3-f1cb-4290-9bb3-b0159630b24d)

@chrjorgensen, I'll need your help for one translation 😄 

### How to test
- Try `Add to library list` action from:
  - A library from the `User Library List` view
  - A filter from the `Object Browser`
  - A .lib object from the `Object Browser`
  - The `User Library List` view's title
- Try `Set as current library` action from:
  - A library from the `User Library List` view
  - A filter from the `Object Browser`
  - A .lib object from the `Object Browser`

### Checklist
* [x] have tested my change

2024-03-03 19:54 UTC, chrjorgensen requested changes
Nice enhancement, @sebjulliand ! :+1: 

I translated the new error message to Danish and changed a command title to title case.

It's working as expected - only one issue was found:
- filters having multiple libraries
  - Add to Library List returns error `Library is too long.`
  - Set to Current Library does nothing

In addition, the context menu item `Add to Library List...` does not prompt the user for any information and should not have `...` in the end... however, when it's run from the command Palette, it prompts the user and should have `...`.
AFAICT the only solution to this situation is two commands with a correct title - where one should only be for the title and should call the other for the action. Too much trouble?

2024-03-03 21:21 UTC, sebjulliand commented
You're right @chrjorgensen, as always!
I introduced a new type (`WithLibrary`) and modified the object browser's items context so the library related actions (including `Create source file`) while only appear on library nodes. This gives a better UX and a cleaner code overall.

I updated the description of the PR accordingly.

2024-03-04 07:45 UTC, chrjorgensen commented on package.json
> +				"category": "IBM i"
A few tabs appending the line...

2024-03-04 07:47 UTC, chrjorgensen commented on src/typings.ts
> +  library:string
```suggestion
  library: string
```

2024-03-04 08:39 UTC, sebjulliand commented
@chrjorgensen formatting done!

2024-03-04 09:02 UTC, chrjorgensen approved these changes
@sebjulliand Works like a charm - and looks good! 🎉

2024-03-04 09:05 UTC, merged