Replace all toUpperCase whith IBMi.upperCaseName where relevant
codefori/vscode-ibmi pull request #1941
Opened 2024-03-19 12:55 UTC by sebjulliand

### Changes
Fixes https://github.com/codefori/vscode-ibmi/issues/1935

The previous PR did not cover all the use cases for object names with a `à` on a connection with CCSID 297.
This PR replaces all the calls to `toUpperCase`/`toLocaleUpperCase` applied to object/member names with `IBMi.upperCaseName`. It fixes the issues where `à` gets wrongly upper cased.

### How to test this PR
1. Connect with CCSID 297
2. Create a library with a name containing `à`
3. In this library, create a source file with a name containing `à`
4. In this source file, create a member with a name containing `à`
5. Run actions from the library list view and object browsers on these items

### Checklist
* [x] have tested my change

2024-03-19 14:42 UTC, worksofliam commented
@sebjulliand Can you confirm the test cases are passing?

2024-03-19 16:01 UTC, sebjulliand commented
> @sebjulliand Can you confirm the test cases are passing?

They do, save for the `Create programs...` ones, but it doesn't seem related.
I also fixed the `runCommand ILE` that was based on a localized output.
And I added a test case for `upperCaseName`.

2024-03-19 17:13 UTC, chrjorgensen commented on src/webviews/settings/index.ts
> +                        .map(item => item.startsWith('/') ? item : connection?.upperCaseName(item) || item.toUpperCase())
@sebjulliand Is this for satisfying TypeScript? Isn't the connection always available?

2024-03-19 21:02 UTC, chrjorgensen requested changes
@sebjulliand I have tested the following with success:

- creating a library called `TESTà`
- creating a source file called `TESTàGAIN` in `TESTà`
- creating a member called `TESTà.RPGLE` in source file `TESTà/TESTàGAIN`
- changing the description on the library, source file and member

However, resolving a member in an INCLUDE statement fails with the following output:

```
/home/<user>: for f in /QSYS.LIB/QGPL.LIB/TESTàGAIN.FILE/TESTÀCOPY.MBR /QSYS.LIB/QGPL.LIB/TESTàGAIN.FILE/TESTÀCOPY.MBR /QSYS.LIB/QTEMP.LIB/TESTàGAIN.FILE/TESTÀCOPY.MBR /QSYS.LIB/TESTà.LIB/TESTàGAIN.FILE/TESTÀCOPY.MBR; do if [ -f $f ]; then echo $f; break; fi; done
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```

Seems like the member name is converted to uppercase using normal uppercase routines... 

@worksofliam Is it the RPGLE extension that does this? I think so...

@sebjulliand Maybe your new uppercase function needs to be exposed to the other extensions? I guess the CL extension and maybe others are hit as well.

2024-03-20 02:27 UTC, worksofliam commented
@chrjorgensen It looks like Seb is correctly using his function in the `memberResolve` method:

https://github.com/codefori/vscode-ibmi/pull/1941/files#diff-e1962db673dbf505e2c74deb034072677a2b4fca832d78a983eebeecac55df85R782

But, I have found where we are uppercasing in the vscode-rpgle extension for the member. I have removed that uppercase call to let the `memberResolve` API handle it, since Seb made the change above.

https://github.com/codefori/vscode-rpgle/commit/493643329c7120c6edb72543d34818c508ab6833#diff-0a08da2f6168c85dd231fc09362ce0c8ead2626b37926c63738004aee6b90a39R88

I am doing a release of vscode-rpgle, in which you should be able to test again with vscode-rpgle 0.26.3.

2024-03-20 08:09 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +                        .map(item => item.startsWith('/') ? item : connection?.upperCaseName(item) || item.toUpperCase())
It is weird, but it's not to satisfy TypeScript - connection can be `undefined` here if you change your settings while not connected.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/fc18493f-2ff9-49db-baa2-9727587982cf)

2024-03-20 10:06 UTC, chrjorgensen approved these changes
@sebjulliand In addition to my tests from yesterday, I've run the following tests:

- rename member `TESTà.RPGLE`
- compile member `TESTà.RPGLE`
- search sourcefile `TESTà/TESTàGAIN`

All tests ran fine.

The failing tests yesterday are not caused by this change, but stem from other extensions / issues.

So I will approve this one - merge at will... 👍

2024-03-20 10:45 UTC, sebjulliand commented
Thank you guys! Let's gooooo!

2024-03-20 10:45 UTC, merged