Major API cleanup
codefori/vscode-ibmi pull request #1968
Opened 2024-04-02 21:38 UTC by worksofliam

### Changes

This is a fairly large API change, but I think a good one. At a high level, here are the biggest changes:

#### CCSID and SQL logic

* `runSQL` was moved from `IBMiContent` and into `IBMi`. It made more sense here as we need to run SQL statements during the connection.
    * The `runSQL` in `IBMiContent` was marked as deprecated, but maps to the new implementation in `IBMi`.
* `qccsid` and `userDefaultCCSID` were made private so they could not be changed in code and only altered during connection.
* New method `getEncoding` returns whichever CCSID should be used. This takes both the QCCSID and user default CCSID. So instead of each API determining if our subsequent calls should use QCCSID or default CCSID, this API does it for you. You will see this is used in `runSQL`.

#### `enableSQL` config

* The user config for `enableSQL` has been removed.
* It was replaced with a getter with the same name, `enableSQL`, in the `IBMi` class.
* `enableSQL` will return `true` when these two conditions are met: the SQL runner is available and the user has a valid CCSID (which we determine thanks to `getEncoding`)
* All references to `config.enableSQL` have been replaced with `connection.enableSQL`
* Notice that there is also a setter for `enableSQL`. This is used for two reasons:
    * Seems like we actually toggle `enableSQL` in some places (namely the QSYS FS provider)
    * We need a way to toggle it for our test cases to ensure some components can work without SQL. Though this did expose to me that `getMemberList` used SQL even when it was disabled. I had to update a test case for that instance. We now expect it to crash when SQL is disabled. **Is this a problem?**

### How to test this PR

1. Run the test cases.
2. Try using the extension as normal.
3. Test our extension API. Seems like the Db2 for IBM i extension continued to work as normal with these API changes.

The failing test case here ('Write tab to member using SQL') is a known issue and is not affected by this PR.

<img width="282" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/7a3b397d-caaa-4ac2-b0c1-ae6652e4e2f5">

### Checklist

* [ ] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-04-11 20:05 UTC, sebjulliand commented on src/api/IBMi.ts
> +    const fallback = ((this.runtimeCcsid < 1 || this.runtimeCcsid === 65535) && this.userDefaultCCSID > 0 ? true : false);
As much as I love ternaries, this is already a boolean expression 😅
```suggestion
    const fallback = (this.runtimeCcsid < 1 || this.runtimeCcsid === 65535) && this.userDefaultCCSID > 0;
```

2024-04-11 20:27 UTC, sebjulliand requested changes
Looks good to me @worksofliam !
The code is OK (save for a very small suggested change) and it all runs fine.
I guess it's unrelated, but there is the `Test getTable (SQL compared to nosql)` test that fails because all the numeric fields are strings in tableB, making deepEqual to fail.

```js
// added by liam
Object.keys(tableA[0]).forEach(k => {console.log({k, a: tableA[0][k], b: tableB[0][k], at: typeof tableA[0][k], bt: typeof tableB[0][k]})})
```

Anyway, just see that small suggestion and we can merge afterwards. Good job, I love a good cleanup!

2024-04-12 03:48 UTC, worksofliam commented
@sebjulliand Fixed your suggestion - thanks!

I also tried to fix that issue but there is a deeper issue that the CSV parser and our `db2Parse` handle the results differently :cry: Agreed, another PR.

2024-04-12 07:12 UTC, sebjulliand approved these changes
Approved! Merge whenever you want. 😎

2024-04-12 12:59 UTC, merged