Cleanup/connection_manager_api
codefori/vscode-ibmi pull request #1975
Opened 2024-04-04 23:37 UTC by worksofliam

### Changes

Replaces raw access of `connections` setting and password context with a `ConnectionManager` namespace.

### How to test this PR

1. Ensure the same test cases pass
2. Try out the extension as normal
3. Confirm debug still works

### Checklist

* [ ] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-04-20 14:06 UTC, sebjulliand commented on src/api/Configuration.ts
> +    if (connections) {
`connections` is never falsy, no need to test it.

2024-04-20 14:07 UTC, sebjulliand commented on src/api/Configuration.ts
> +    let connections = getAll();
Never use `let` unless it's absolutely necessary 😉
```suggestion
    const connections = getAll();
```

2024-04-20 14:08 UTC, sebjulliand commented on src/api/Configuration.ts
> +    const connectionKey = `${connectionName}_password`;
Since `${connectionName}_password` is repeated three times, create a small function to encompass the logic.

2024-04-20 16:42 UTC, sebjulliand commented on src/webviews/login/index.ts
>          if (!disconnect()) return false;
We're missing an `await` here.
```suggestion
        if (!await disconnect()) return false;
```

2024-04-20 16:47 UTC, sebjulliand commented on src/views/ConnectionBrowser.ts
> +            let { index, data } = existingConnection!
Since we don't reuse `existingConnection`...
```suggestion
            let { index, data } = ConnectionManager.getByName(server.name)!;
```

2024-04-20 16:53 UTC, sebjulliand commented on src/views/ConnectionBrowser.ts
> +    return (ConnectionManager.getAll() || [])
`getAll` already returns an array no matter what.
```suggestion
    return ConnectionManager.getAll()
```

2024-04-20 16:56 UTC, sebjulliand commented on src/extension.ts
> +    const connections = (ConnectionManager.getAll() || []);
`getAll` always returns an array.
```suggestion
    const connections = ConnectionManager.getAll();
```

2024-04-20 17:13 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +                await ConnectionManager.updateByIndex(index, stored);
We should refresh the browser here to update the connection node name/description.
```suggestion
                await ConnectionManager.updateByIndex(index, stored);
                vscode.commands.executeCommand(`code-for-ibmi.refreshConnections`);
```

2024-04-20 17:31 UTC, sebjulliand requested changes
Nice cleanup @worksofliam ! Way cleaner than the raw accesses we used to do. I love it!
See the few comments I made, mostly code cleanup.

One thing to consider: since we update by index, there is a use case where the data can be saved on the wrong index:
- Open the settings of a connection and keep it opened
- Sort the connections browser
- Save the opened settings

Since the indexes were changed while sorting, the index kept by the settings editor is not the right one anymore.
I admit it's an edge case...but if I thought of it, someone else will.
So maybe we should set a context value while the webview is opened to prevent the sort and rename actions from being executed.

2024-05-07 15:17 UTC, worksofliam commented
@sebjulliand Sorry this took SO long. I went ahead and used `withContext` around the UI logic to disable the buttons. Check it out and let me know - thanks!

2024-05-13 20:23 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +            const ui = await new CustomUI()
No need to `await`
```suggestion
            const ui = new CustomUI()
```

2024-05-13 20:37 UTC, sebjulliand commented
@worksofliam I'll fix a small issue here with `withContext`; in the meantime, how about adding that brilliant use of it to disable the buttons and disable `code-for-ibmi.connectTo`, `code-for-ibmi.connectToAndReload`, `code-for-ibmi.renameConnection`, `code-for-ibmi.deleteConnection` as well? WDYT?

2024-05-13 20:44 UTC, sebjulliand requested changes
@worksofliam works like a charm! Brilliant cleanup!
Just see my last comment about disabling more commands to avoid potential issues and then we'll be good to go!

2024-05-13 20:59 UTC, worksofliam reviewed
@sebjulliand I went ahead with your suggestion, and some other commands also. Thanks!

2024-05-13 21:19 UTC, sebjulliand requested changes
Not sure about disabling "code-for-ibmi.showAdditionalSettings" and "code-for-ibmi.showLoginSettings"; it doesn't seem to be risky to open multiple editors (sorry...)

2024-05-14 13:10 UTC, sebjulliand approved these changes
Approved and merged! 😎

2024-05-14 13:10 UTC, merged