Fix update path logic
codefori/vscode-ibmi pull request #1977
Opened 2024-04-05 18:52 UTC by jonnyz32

### Changes

Make sure that the path popup doesn't complain if /usr/bin or /QOpenSys/usr/bin not in path. I have a 7.3 ibmi without /QOpenSys/usr/bin on the path.

2024-04-08 13:45 UTC, worksofliam commented
@jonnyz32 Can you please provide a sample `.profile` that we can use to test this?

2024-04-08 14:46 UTC, jonnyz32 commented
@worksofliam How about this?
```
export PATH="/QOpenSys/pkgs/bin:/opt/homebrew/opt/libpq/bin:/Users/zakjonat/Downloads:/usr/local/mysql/bin:/Users/zakjonat/.nvm/versions/node/v20.0.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/share/dotnet:/home/AURORAJPN2/.dotnet/tools:/usr/local/go/bin:/opt/podman/bin:/opt/homebrew/opt/libpq/bin:/Users/zakjonat/Downloads:/usr/local/mysql/bin:/Users/zakjonat/.nvm/versions/node/v20.0.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin"
```

2024-04-16 14:16 UTC, worksofliam commented
@jonnyz32 Any chance you can fix the conflict here?

2024-06-17 13:22 UTC, jonnyz32 commented
@worksofliam Done

2024-06-18 11:59 UTC, worksofliam commented
@jonnyz32 

Had some deliberations, and we think it better that, instead of ignoring this entry, that really it might be required by Code for IBM i. We actually use some executables in that directory in Code for IBM i, and we don't qualify the paths, so we are kind of assuming it might be on there.

Therefore, it might be a risk if we merge this and have things stop working. It is recommended to append `/usr/bin` to your list so other items are picked up first.

2024-06-18 12:53 UTC, jonnyz32 commented
@worksofliam I have made some changes to my pr to now ensure the user has these required paths, instead of ignoring it. Let me know what you think.

2024-06-18 13:28 UTC, worksofliam commented
@jonnyz32 Thanks - it's quite a change from the original PR requirement. Any chance you can update the PR body to reflect what the PRs intention is? Thanks!

2024-06-18 13:35 UTC, jonnyz32 commented
@worksofliam Done

2024-06-20 16:44 UTC, worksofliam requested changes
@jonnyz32 Something isn't right. I deleted my existing `.bashrc`, connected and reloaded, and now gets created like this:

```sh
# Generated by Code for IBM i
export PATH=/QOpenSys/pkgs/bin:$PATH:/QOpenSys/usr/bin:/usr/bin
```

Guessing `$PATH` should come at the end? Or is this intended?

2024-06-20 16:50 UTC, jonnyz32 commented
@worksofliam I intended /QOpenSys/usr/bin:/usr/bin to come after $PATH as I didn't want it to overwrite the priority on their original path. I am wondering why the $PATH variable wasn't expanded in the bashrc though, or is it supposed to be like that?

2024-06-20 16:52 UTC, worksofliam commented
@jonnyz32 Yes, we don't expand the `$PATH` variable, we just place it in like that so we don't affect the users own `PATH`.

https://github.com/codefori/vscode-ibmi/pull/1977/files#diff-af91aaa8436f73c4457121b35da47e46d53459b47f044b7dbdb78ea785cb1824R783

2024-07-09 18:57 UTC, jonnyz32 commented
@worksofliam Is there anything you want changed still?

2024-07-09 19:02 UTC, worksofliam commented
@jonnyz32 Nope. If what I shared is what you expected, this can probably be merged.

Thanks!

2024-07-09 21:29 UTC, chrjorgensen requested changes
@jonnyz32 One issue found during review:

When `/QOpenSys/usr/bin` or `/usr/bin` is not found in PATH, the warning dialog appears as expected. But when the user accepts to have `.bashrc` _updated_ (because it already exists), none of the two directories are appended to the `export PATH` line...?

Seems like you didn't change the code for updating an existing `.bashrc` file, since the code still only mentions `/QOpenSys/pkgs/bin`?

2024-07-10 14:25 UTC, jonnyz32 commented
> @jonnyz32 One issue found during review:
> 
> When `/QOpenSys/usr/bin` or `/usr/bin` is not found in PATH, the warning dialog appears as expected. But when the user accepts to have `.bashrc` _updated_ (because it already exists), none of the two directories are appended to the `export PATH` line...?
> 
> Seems like you didn't change the code for updating an existing `.bashrc` file, since the code still only mentions `/QOpenSys/pkgs/bin`?

Good catch. Just fixed this issue. Ran a small test to confirm.
.bashrc before
```
-bash-5.2$ cat ~/.bashrc
export PS1="\u@\h \W:\$ "
export PATH=$PATH:/QOpenSys/pkgs/bin
```
.bashrc after
```
-bash-5.2$ cat ~/.bashrc
export PS1="\u@\h \W:\$ "
export PATH=/QOpenSys/pkgs/bin:$PATH:/QOpenSys/usr/bin:/usr/bin
```

2024-07-19 08:48 UTC, chrjorgensen requested changes
@jonnyz32 Only a small error left to fix... 😉 

The code will add both `/usr/bin` and `/QOpenSys/usr/bin` to the PATH if one of them is missing, resulting in duplicate PATH entries... this is acceptable, since it is allowed in the shell...

2024-07-19 08:48 UTC, chrjorgensen commented on src/api/IBMi.ts
> +                                      .replace("::", ":")}/QOpenSys/usr/bin:/usr/bin`; //Removes double : in case /QOpenSys/pkgs/bin wasn't at the end
@jonnyz32 You're missing a `:` here:
```suggestion
                                      .replace("::", ":")}:/QOpenSys/usr/bin:/usr/bin`; //Removes double : in case /QOpenSys/pkgs/bin wasn't at the end
```

I tested with a PATH not having `/QOpenSys/usr/bin` in it, and I ended up with this:
```shell
export PATH=/QOpenSys/pkgs/bin:/usr/bin/QOpenSys/usr/bin:/usr/bin
```
Note the `/usr/bin/QOpenSys/usr/bin` in the path!

2024-07-19 14:18 UTC, jonnyz32 commented
> @jonnyz32 Only a small error left to fix... 😉 ...see comment in code below...
> 
> Another issue is that the code will add both `/usr/bin` and `/QOpenSys/usr/bin` to the PATH if one of them is missing, resulting in duplicate PATH entries... but this is acceptable, since it is allowed in the shell...

Thanks, I committed your suggestion :)

2024-07-19 15:05 UTC, chrjorgensen approved these changes
@jonnyz32 Approved and merged - thanks! 👍

2024-07-19 15:05 UTC, merged