Debug service configuration and management improvement
codefori/vscode-ibmi pull request #1990
Opened 2024-04-16 16:19 UTC by sebjulliand

### Changes
This PR fixes a number of potential issues related to the debug service and the way certificate and startup is managed.

- The certificate generated by the extension used the connection settings' hostname as the certificate password. The password is now randomly generated.
- Since the password used to be deterministic, it was re-encrypted every time the debug service was started. Re-encrypting it was mandatory since starting the debug service would destroy the password's encryption key (as designed by IBM). To avoid providing the password every time the service starts and to allow it to be started outside of VSCode, the encrypted password is now saved in the service's configuration and the encryption is backed up so it can be reused every time the `startDebugService.sh` is executed.
- The method above prevents an issue that could arise if two users with a different hostname for the same LPAR would try to start the debug service (only the user who generated the certificate could start the service).
- A new `DebugConfiguration` class has been introduced to manage the debug service configuration.
- Previously generated certificate are migrated when the connection is established (legacy certificates included)
- The `debug_service.crt` file is not deleted anymore. It is easier to keep it for clients to download it than generating it (as it requires the certificate's password). The `debug_service.crt` is re-generated when existing certificate are migrated or imported.
- The feature designed to import a certificate for the service has been fixed.
- Importing a certificate is now offered to the user if no certificate exists for the service.
- There is now a single method to check the client certificate state: it checks if it exists and if it matches the remote certificate.
- The Debugger section of the settings no longer allows to specify a certificate path and debug ports. These values are read from the service configuration.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/782a3a93-6eb2-4b9d-af4a-8e730e805eb9)
- If debug is not managed, a new inline action located on the debug service node in the `IBM i debugger` view allows to open the service configuration file.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/b775a4a1-fd50-41e9-b00c-20a4ad38e719)
- With all of the above, the debug service can be started from Code for IBM i or from anywhere else just by running the `startDebugService.sh` script. It requires no external parameters or environment variables anymore. For example, it can be started using this command:
```
SBMJOB CMD(STRQSH CMD('/QOpenSys/pkgs/bin/bash -c /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh')) JOB(DBGSVCE) JOBQ(QSYS/QUSRNOMAX) JOBD(QSYS/QSYSJOBD)`
```

### How to test this PR
Before you start testing this PR, backup your existing debug service certificate so you can:
- restore it if something goes wrong 😅
- use it to test the Import feature

#### Certificate migration
1. Connect to a system with an existing debug service certificate
2. Check the certificate is migrated to the path defined in the debug service configuration file
3. Check the client certificate is generated
4. Check the configuration file is updated with the `DEBUG_SERVICE_KEYSTORE_FILE`, `DEBUG_SERVICE_KEYSTORE_PASSWORD` and `CODE4IDEBUG` values.

#### Certificate import
1. Delete the existing certificate for the service
2. Click on the action to fix the debug service in the debugger view
3. Select the import action
4. Follow the instructions on screen
5. Check if everything is ok (steps 2 to 4 above)

#### New certificate
1. Delete the existing certificate for the service
2. Click on the action to fix the debug service in the debugger view
3. Select the generate action
5. Check if everything is ok (same as above)

### Checklist
* [x] have tested my change
* [ ] updated relevant documentation

2024-04-16 19:16 UTC, worksofliam commented on src/api/IBMiContent.ts
> +  async streamFileExists(path: string) {
Is this really any different from our `testStreamFile` API? Should we use that instead?

2024-04-16 19:54 UTC, worksofliam commented on src/api/debug/certificates.ts
> +export async function setup(connection: IBMi, imported?: ImportedCertificate) {
Additional comments on setup would be nice. I know we're going to have to change this in the future.

It seems to me like this is entry point and what does all the setup for the debug service certificates.

2024-04-16 19:56 UTC, worksofliam commented on src/api/debug/index.ts
> +                detail: `Debug service certificate does not exist on the system or it needs to be re-created. You can either import an existing certificate or generate one. Then the client certificat
Should we be more explicit here about which debug certificate? E.g. server/client certificate.

2024-04-16 19:56 UTC, worksofliam commented on src/api/debug/index.ts
> +                      title: `Select debug service certificate`,
Perhaps 'Select debug service server certificate'?

2024-04-16 20:01 UTC, worksofliam requested changes
Check out my initial questions/comments. Initial testing looks ok, but need to dive deeper into your provided scenarios.

2024-04-16 20:19 UTC, sebjulliand commented on src/api/debug/certificates.ts
> +export async function setup(connection: IBMi, imported?: ImportedCertificate) {
Agreed

2024-04-16 20:42 UTC, sebjulliand commented on src/api/debug/index.ts
> +                      title: `Select debug service certificate`,
👍🏻

2024-04-19 15:17 UTC, worksofliam commented
Got this issue: 

![image](https://github.com/codefori/vscode-ibmi/assets/3708366/001d2514-3a61-42ae-abe1-9d7ac3c74591)

2024-04-20 13:59 UTC, sebjulliand commented
> Got this issue:
> ...

It's still working fine here on a couple of LPAR.
@worksofliam Is this with debug v2 installed?
The `key.properties` file is generated by the `encryptKeystorePassword.sh` script after it has been executed. `cp` is run in the debug service working directory, where the file is supposed to be found.
Can you share your output after you get that error?

2024-04-23 12:51 UTC, worksofliam commented
When trying to start the debug service as a *PGMR:

<img width="492" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/d7c927e4-6d32-4a9c-beae-4b29d96d3976">

```
/QIBM/UserData/IBMiDebugService: export MY_JAVA_HOME="/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit" && /QOpenSys/usr/bin/nohup "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh"
/home/JOEUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(37)');
select distinct job_name, local_port from qsys2.netstat_job_info j where job_name = (select job_name from qsys2.netstat_job_info j where local_port = 8005 and remote_address = '0.0.0.0' fetch first row only)
{
    "code": 1,
    "signal": null,
    "stdout": "Environment variable DEBUG_SERVICE_KEYSTORE_FILE is not set.",
    "stderr": "java version \"1.8.0_401\"\nJava(TM) SE Runtime Environment (build 8.0.8.20 - pap6480sr8fp20-20240112_01(SR8 FP20))\nIBM J9 VM (build 2.9, JRE 1.8.0 OS/400 ppc64-64-Bit Compressed References 20231219_62619 (JIT enabled, AOT enabled)\nOpenJ9   - 08d2144\nOMR      - 7a5005b\nIBM      - 7394519)\nJCL - 20231221_01 based on Oracle jdk8u401-b10"
}
```

2024-04-23 18:22 UTC, worksofliam commented
@sebjulliand I am getting this in the 2.9.2 pre-release when I open the new IBM i Debug view we added. Is this something we should take care of in this PR?

![image](https://github.com/codefori/vscode-ibmi/assets/3708366/1fa6838c-6e4c-4a1f-8a2f-fa696ca9bb0d)

```
/QIBM/UserData/IBMiDebugService/certs: openssl pkcs12 -in /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx -passin pass:UT201P18.RCH.STGLABS.IBM.COM -info -nokeys -clcerts 2>/dev/null | openssl x509 -outform PEM
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "unable to load certificate\n4294967296:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE"
}
```

2024-04-23 18:28 UTC, worksofliam commented
Here is the key issue I was getting the other day. This is using a v2 PTF:

<details>
<summary>Click me</summary>

```
/QIBM/UserData/IBMiDebugService/certs: openssl genrsa -out debug_service.key 2048 && openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=system' && openssl x509 -req -in debug_service.csr -signkey debug_service.key -out debug_service.crt -days 1095 -sha256 -req -extfile <(printf "subjectAltName=DNS:system,IP:9.5.12.241") && openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:O_FYmyevZLd8ae4LRb6LDfqDUtZKeUVokpZo8VcrXo15nsAnoYvW && rm debug_service.key debug_service.csr && chmod 444 debug_service.*
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "Certificate request self-signature ok\nsubject=CN = system"
}

/home/LIAM: export DEBUG_SERVICE_KEYSTORE_PASSWORD="O_FYmyevZLd8ae4LRb6LDfqDUtZKeUVokpZo8VcrXo15nsAnoYvW" && /QIBM/ProdData/IBMiDebugService/bin/encryptKeystorePassword.sh | /usr/bin/tail -n 1
{
    "code": 0,
    "signal": null,
    "stdout": "Incorrect Java version. Java 11 is required.",
    "stderr": ""
}

/QIBM/UserData/IBMiDebugService: cp key.properties .code4i.debug
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "cp: cannot stat 'key.properties': A file or directory in the path name does not exist."
}
```

</details>

2024-04-23 20:51 UTC, sebjulliand commented
> Here is the key issue I was getting the other day. This is using a v2 PTF:
> ...

@worksofliam I found the problem: I forgot to add java home to the env when running the encryption script. Since it failed, no key was generated. It's funny the script returned a code 0 and the error in stdout though...

2024-04-23 22:18 UTC, sebjulliand commented
@worksofliam I pushed a fix for your encryption issue on v2. It should be fine if you test after you pull the branch.
Also, the user that starts the service now needs to have `*ALLOBJ` to start it.

2024-04-24 17:20 UTC, worksofliam commented on src/api/IBMi.ts
> +  async checkUserSpecialAuthorities(authorities: ("*ALLOBJ" | "*AUDIT" | "*IOSYSCFG" | "*JOBCTL" | "*SAVSYS" | "*SECADM" | "*SERVICE" | "*SPLCTL")[], user?: string) {
I don't think this API should throw an error. I do think that it should instead return a valid result.

Perhaps `{valid: boolean, missing: string[]}`. I also think we need a type for the list of authorities.

2024-04-24 17:24 UTC, worksofliam requested changes
Code is looking good other than one comment I left above. Check it out and let me know what you think. The last remaining thing is some additional test cases we need to ensure:

2024-04-24 17:29 UTC, worksofliam commented
Test cases:

## Ensure it works with v1 debug:

* [ ] Generating certificates working
* [ ] Using existing certificates working
* [ ] Batch debug works

## Ensure it works with v2 debug:

* [ ] Generating certificates working
* [ ] Using existing certificates working
* [ ] Batch debug works
* [ ] SEP debug works

2024-04-24 17:35 UTC, sebjulliand commented on src/api/IBMi.ts
> +  async checkUserSpecialAuthorities(authorities: ("*ALLOBJ" | "*AUDIT" | "*IOSYSCFG" | "*JOBCTL" | "*SAVSYS" | "*SECADM" | "*SERVICE" | "*SPLCTL")[], user?: string) {
Sounds reasonable. Let's do this.

2024-04-24 20:24 UTC, sebjulliand commented
> Code is looking good other than one comment I left above. Check it out and let me know what you think. The last remaining thing is some additional test cases we need to ensure:

Thanks a lot @worksofliam !
Done as asked: the checkAuth API now returns a result. I also straightened the rights on the certificates related files.
We should be fine now 😄

2024-04-25 13:20 UTC, worksofliam approved these changes

2024-04-25 13:22 UTC, merged