Feature/uri_cleanup
codefori/vscode-ibmi pull request #2038
Opened 2024-05-07 14:57 UTC by worksofliam

### Changes

* [ ] Add new url for opening files at a specific path
* [ ] Add improved error handling in the new URI
* [ ] When the host is provided, but the user is not connected, then automatically connect if the connection is defined

### How to test this PR

* `vscode://halcyontechltd.code-for-ibmi/open?path=/home/liama/xyz`
* `vscode://halcyontechltd.code-for-ibmi/open?host=1.1.1.1&path=/home/liama/xyz`

Examples:

1. Run the test cases
2. Expand view A and right click on the node
3. Run 'Execute Thing' from the command palette

### Checklist

* [ ] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-06-07 16:39 UTC, julesyan commented
If they have no current connection would it beneficial to allow the user to pick one? Instead of a warning message. 

Also I am unsure the purpose of the host param as the below two scenarios arent covered:
- **Scenario 1**: if you arent connected it doesnt auto connect to the given host, isntead it just gives a warning it cannot open the file. I think it should ask to auto connect if the given host is on the list. If the host is listed more than once then give me the option to pick which connection to initiate
- **Scenario 2**: if you are connected to the wrong host, it just prompts to open with the current connection. We should also have the option to switch to the correct connection, again if there is more that one listed conneciton to the same host then allow me to pick which connection to initiate

2024-06-17 17:32 UTC, worksofliam commented
@julesyan Thanks for your great testing.

1. Yes, we should automatically connect to the host given it is in the list.
2. Right now we don't even have the internal logic to disconnect and reconnect to a new system automatically. Let me see if this is even possible (since we do have APIs to do both separately.)

2024-09-11 15:29 UTC, julesyan commented
Tested locally and found no more issues, looks good!

2024-09-19 15:31 UTC, SanjulaGanepola requested changes
@worksofliam I did some testing with this change and noticed a few issues. Refer to my comments below.

2024-09-19 15:31 UTC, SanjulaGanepola commented on src/uri/index.ts
> +              window.showWarningMessage(t(`uriOpen.noConnection`));
```suggestion
              window.showWarningMessage(t(`uriOpen.missingPath`));
```

2024-09-19 15:31 UTC, SanjulaGanepola commented on src/uri/index.ts
> +                window.showWarningMessage(t(`uriOpen.missingPath`));
Given the example you gave in this PR:
```
vscode://halcyontechltd.code-for-ibmi/open?path=/home/liama/xyz
```
I assume this means that the file will be opened based on the active connection. If so, is this else block a mistake because this will not open any file and just give this warning even though I am connected. In the case there is no connection, shouldn't the message be:
```ts
window.showWarningMessage(t(`uriOpen.noConnection`));
```

2024-11-22 13:34 UTC, varunrao1991 commented
Can you create an artefact for this PR?

2025-01-18 15:11 UTC, closed without merging

2025-08-20 13:53 UTC, ptc-abrown commented
This works wonderfully with vscode.open command but fails with vscode.diff when you hand in 2 uris. "open <-> open" error.

I have not put a debugged on the code to try to understand why.

2025-08-20 13:58 UTC, sebjulliand commented
> This works wonderfully with vscode.open command but fails with vscode.diff when you hand in 2 uris. "open <-> open" error.
> 
> I have not put a debugged on the code to try to understand why.

What URIs are you using with `vscode.diff`?

2025-08-20 15:05 UTC, ptc-abrown commented
Called from another extension through executeCommand.

vscode.commands.executeCommand(`vscode.diff`, thisURI, thatURI)

Where thisURI and thatURI would work fine with vscode.open.

In my case 2 fully described member objects on the same host (I did not try 2  different hosts at all because code-for-i would need 2 instances to do that.

vscode://halcyontechltd.code-for-ibmi/open?host=<host>&user=<user>&connect=true&path=AR_QAC/QDDSSRC/ARCMNTD.DSPF

vscode://halcyontechltd.code-for-ibmi/open?host=<host>&user=<user>&connect=true&path=AR_QAC/QDDSSRC/ARCMSTD.DSPF

It did not escape my attention that the URI has "open" in it but I had hoped the end result was a stream of some sort that would send the file content to vscode to open in an editor or open in diff. Looking at source, it suggests to me that it dos not return a file to vscode but rather opens an editor (which I also need).

I had hoped to find a way to copy the file locally but I did not see that in the exposed code-for-i interface or any commands I could call.

I am not picky about how I do this.

2025-08-20 15:35 UTC, sebjulliand commented
Well, the `/open` URI is not meant to be called like this, I'm afraid. Its main purpose it to be able to open an editor on a member/IFS File, and connect to a system if needed, in one single call. It could be used to open a source member from an external Web application, for example.

`vscode.open` and `vscode.diff` expect URis that are provided by a VS Code File System. Code for IBM i provides two file systems: `member://` and `streamfile://`. You can refer to [this documentation](https://codefori.github.io/docs/dev/examples/#get-members-and-streamfiles) to see how these URI are built.

If your goal is to copy streamfiles/members locally, without opening an editor, then you could:
- Do it without using the exported API, just by using the `member` or `streamfile` URI described above in conjunction with VS Code's `vscode.workspace.fs.copy` method.
- With [Code for i exported API](https://codefori.github.io/docs/dev/api/), once you get the reference to `instance` as described in the documentation, use `instance.getConnection()?.getContent().downloadStreamfileRaw` or `instance.getConnection()?.getContent().downloadMemberContent`. You'll need a bit of plumbing using VS Code API to save the content locally, but it should be fairly easy.

Hope this helps!