Refresh file
codefori/vscode-ibmi pull request #2042
Opened 2024-05-08 23:22 UTC by julesyan

### Changes
Added the ability to refresh an IFS file. Button is located in the top right of the editor, similar to Run Actions. Making use of the pre-existing command `workbench.action.files.revert` from VSCode

### How to test this PR
1. Open an IFS file
2. Make/Trigger changes to the file elsewhere 
3. Click refresh button, file should update with latest content

### Checklist
* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-05-09 10:12 UTC, chrjorgensen requested changes
@julesyan Thank you very much for your first contribution - a great idea and implementation! 😍 

One small addition to make it work for members also - and I think we're good to go... 🙏

2024-05-09 18:50 UTC, chrjorgensen requested changes
Excellent - works for members now also. 👍 

One caveat that needs to be addressed before we can send it out: All changes in a member or streamfile is lost without warning, when the refresh icon is pressed!

Is there a way to warn the user about this? And save or discard the changes before refreshing?

2024-05-10 13:34 UTC, worksofliam commented
@chrjorgensen @julesyan 

> Is there a way to warn the user about this? And save or discard the changes before refreshing?

This is a great point. I am guessing we might have to define our own command, which wraps a warning if the document is dirty before executing the command programmatically.

Julia, take a stab at that if you want - and feel free to reach out and I can offer my help whenever!

2024-05-13 13:21 UTC, worksofliam commented on src/instantiate.ts
> +    vscode.commands.registerCommand("code-for-ibmi.refreshFile", async () => {
I believe there is a parameter here, of type `vscode.Uri` because it is being called from `editor/title`.

2024-05-13 13:21 UTC, worksofliam commented on src/instantiate.ts
> +        const editor = vscode.window.activeTextEditor;
I think instead of using `activeTextEditor`, you should get the editor based on the provided URI parameter. 

We have `Tools.findExistingDocumentUri` to get a document based on URI.

2024-05-13 13:32 UTC, julesyan commented on src/instantiate.ts
> +    vscode.commands.registerCommand("code-for-ibmi.refreshFile", async () => {
So I also let it stay in the command palette, I forgot to mention that in the PR. Does that method also give in the same params?

2024-05-14 13:20 UTC, worksofliam commented on src/instantiate.ts
> +          .then(result => {
I believe this should be a modal instead of a traditional warning message.

The second parameter can be a `MessageOptions` object.

2024-05-14 13:36 UTC, worksofliam commented on package.json
> +					"when": "code-for-ibmi:connected && (resourceScheme == streamfile || resourceScheme == member)",
Yup, you're right. Ignore this!

2024-05-14 21:12 UTC, worksofliam requested changes
Functionality is perfect. Last thing we need to do is fix up the locale and then you're done!

2024-05-14 21:12 UTC, worksofliam commented on src/instantiate.ts
> +            `Continue`)
I think your string literals here need to use our translate API. I believe 'Continue' has an id, but might need a new one for the label.

* See `en.json` and add a prop for the label
* Use the `t` API with the IDs in place of the string literals. (`t` comes from `locale.ts`)

2024-05-15 13:31 UTC, sebjulliand commented
> @chrjorgensen @sebjulliand Any chance you can add `discard.changes` for FR and DA when you get a chance? Thanks!

Sure:
```
"discard.changes": "Vos modifications vont être perdues",
```

2024-05-28 08:20 UTC, chrjorgensen approved these changes
@julesyan Finally added the danish translation - sorry for the delay. 😞 

I have tested and reviewed this PR and it works great! Let's get this merged! 😍

2024-05-28 08:20 UTC, merged