Add ability to compare selected or open file with an IFS or local file path
codefori/vscode-ibmi pull request #2049
Opened 2024-05-11 21:10 UTC by julesyan

### Changes
Based on #1902 
- Added ability to compare with local files (even when IBM i is not connected)
  - Context menu item shows in Object Browser and IFS Browser
  - Context menu item also shows in VSCode's File Explorer, it does not show when selecting folders 
  - Command palette uses currently active file
- Added ability to compare with stream files
  - Context menu item shows in Object Browser and IFS Browser
  - Context menu item also shows in VSCode's File Explorer, it does not show when selecting folders 
  - Command palette uses currently active file

### How to test this PR
- compare with local file (IBM i does not need to be connected, except for option 1):
  - Option 1: Right click file in IFS/Object view, select "Compare with local file...", enter in local file path
  - Option 2: Have a file open, open command palette, select "Compare with local file...", enter in local file path
  - Option 3: Rick click file in VSCode's File Explorer view, select "Compare with local file...", enter in local file path
- compare with IFS file (IBM i must be connected): 
  - Option 1: Right click file in IFS/Object view, select "Compare with IFS file...", enter in local file path
  - Option 2: Have a file open, open command palette, select "Compare with IFS file...", enter in local file path
  - Option 3: Rick click file in VSCode's File Explorer view, select "Compare with IFS file...", enter in local file path

### Checklist

* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-05-14 23:09 UTC, julesyan commented
Added ability to compare with Active File: 
- Option 1: Right click file in IFS/Object view, select "Compare with Active File"
- Option 2: Have a file open, open "Go to file..." from Object browser or command palette, click split editor icon on a path
- Option 3: Rick click file in VSCode's File Explorer view, select "Compare with Active File"

2024-05-15 09:19 UTC, sebjulliand commented on .gitignore
> +.vscode/
Why adding `.vscode` to `.gitignore` since it holds useful files?

2024-05-15 09:52 UTC, julesyan commented on .gitignore
> +.vscode/
Oh sorry since it was not in the repository and VSCode generates the folder when working with workspaces, I thought it was ok to ignore.

2024-05-15 09:54 UTC, sebjulliand commented on .gitignore
> +.vscode/
No worries @julesyan 😄 
It is in the repo though! https://github.com/codefori/vscode-ibmi/tree/master/.vscode

2024-05-15 09:56 UTC, julesyan commented on .gitignore
> +.vscode/
Oh! I must have missed it, my git was saying it is a new! Will revert that

2024-05-15 13:15 UTC, worksofliam requested changes
I have left a quick review. Lack of member support is really the only major issue.

Also, can you please also add `code-for-ibmi.compareCurrentFileWithMember`?

2024-05-15 13:15 UTC, worksofliam commented on src/instantiate.ts
> +  let currentFile;
Please add a type on `currentFile`.

2024-05-15 13:15 UTC, worksofliam commented on src/instantiate.ts
> +async function compareCurrentFile(node: any, scheme: `streamfile` | `file`) {
`scheme` must also support `member`.

2024-05-15 13:15 UTC, worksofliam commented on src/instantiate.ts
> +          let path = vscode.Uri.parse(`streamfile:${event.item.label}`);
Hardcoded `streamfile` is not correct here, since `event` can be triggered from a `member` or `streamfile`.

See the logic between 483-509 to see how we determine if it's a `member` or `streamfile` (note that we just check if the label starts with `/` to determine the scheme)

2024-05-17 02:19 UTC, julesyan commented
Added ability to compare with members (IBM i must be connected):
- Option 1: Right click file in IFS/Object view, select "Compare with member...", enter in member path
- Option 2: Have a file open, open command palette, select "Compare with member...", enter in member path
- Option 3: Rick click file in VSCode's File Explorer view, select "Compare with member...", enter in member path

2024-06-22 21:46 UTC, chrjorgensen commented on package.json
> +				"command": "code-for-ibmi.compareCurrentFileWithStream",
Please rename to 
```suggestion
				"command": "code-for-ibmi.compareCurrentFileWithStreamfile",
```

to be more consistent.

2024-06-22 21:51 UTC, chrjorgensen commented on package.json
> +				{
Please move these items into new submenu `Compare with` - menu has become quite long.
Also move the compare menu items below `sourceFileStuff` - action items should be easier to access (i.e. first in the menu).

2024-06-22 22:01 UTC, chrjorgensen commented on src/instantiate.ts
> +            buttons: [compareButton]
The compare button should not be added to libraries...

2024-06-22 22:04 UTC, chrjorgensen requested changes
@julesyan Should we get this PR going? I have made some comments regarding the UX, which I hope you can fix. 🙏

2024-07-01 07:57 UTC, chrjorgensen commented on src/instantiate.ts
> +        compareCurrentFile(node, `streamfile`);
Please fix indentation.

2024-07-01 08:00 UTC, chrjorgensen commented on src/instantiate.ts
> +import { t } from './locale';
`t` is already imported...

2024-07-01 08:27 UTC, chrjorgensen requested changes
@julesyan Only two small issues and then we're good to go! 👍

2024-07-06 12:35 UTC, julesyan commented on src/instantiate.ts
> +import { t } from './locale';
I get errors when i remove it, where is it imported?

2024-07-06 15:16 UTC, chrjorgensen approved these changes
@julesyan Well done - works as expected. :+1: 

Approved and merged.

2024-07-06 15:17 UTC, chrjorgensen approved these changes

2024-07-06 15:18 UTC, merged

2024-07-17 09:28 UTC, chrjorgensen commented
@worksofliam I think this merged PR fixes issue #1902 right?