Allow Save As and breadcrumb navigation
codefori/vscode-ibmi pull request #2060
Opened 2024-05-16 20:47 UTC by sebjulliand

### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/2004

This PR completes the QSYS and IFS FileSystemProviders implementation. By doing so, it allows for `Save As` and the editor breadcrumb navigation to work for members and streamfiles.

The `stat` method had to return an actual result, `createDirectory` and `readDirectory` had to be implemented, `writeFile` had to be modified because Save As first creates an empty file then writes into it.

#### Save As
Streamfiles and members can now be Saved As (using `ctrl+shift+s` or the menu action).

For streamfiles, it works like an usual unix file system. browsing the IFS works from there.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/985aef8c-5514-4811-97aa-3a913d9f0cae)

If the target path doesn't exist, it will be created.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/727a668c-25d0-41e2-8f96-7e51af842496)

Overwriting an existing file asks for a confirmation as expected.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/40b61b1e-89dc-4bcf-bfc1-a9d29508e646)

For QSYS members, it works the same (navigation, creation of target path, overwriting). But since it's a QSYS path, the path must always be in the form of `/LIBRARY/FILE/MEMBER.TYPE`. The library and/or file will be created if needed when saving as.

#### Breadcrumb navigation
Clicking on the part of a path in an editor with a member or streamfile opened will allow to navigate to another location to open another member/stream.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/a545dc4c-b09e-4b2a-b6ca-6182a914cea1)
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/2eba4dd6-0f4a-4418-8af0-ed8a983319ca)

### How to test this PR
- Open a streamfile or a member
- Try navigating from the breadcrumbs
- Try to Save As
  - As a new file in an existing directory/source physical file
  - As a new file in a non existing directory/library/source physical file
  - As an existing file (to overwrite it)

### Checklist
* [x] have tested my change
* [x] Remove any/all `console.log`s I added

2024-05-17 06:40 UTC, chrjorgensen commented
@sebjulliand AMAZING - AND I HAVEN'T EVEN TESTED IT YET! YOU'RE MY HERO!! 😍

2024-05-17 08:39 UTC, chrjorgensen requested changes
@sebjulliand A quick run of this PR shows some issues:

1. I created a library `CODEFORI` and sourcefile `TEST` and member `MEMBER` and added some text. `Save` went fine, but `Save as...` did not: After entering new membername `MEMBER2`, I get this: 
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/9edc808e-fd14-4f1d-84c4-4a8fd9225478)
But this is the only member:
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/6349e143-936f-4b40-8829-4fc4f2254742)

2. I created a directory `/tmp/a` and a streamfile `testing.rpgle`, entered some text and saved. No issue. 
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/cbf70e4c-6b2f-4044-879b-1bda2c07c0ca)
But `Save as...` just shows the directory name:
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/9d37ffe9-745b-4084-b8c5-e7f6dada3137)
When I enter a new name for the streamfile, it always shows this:
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/b17799a8-69af-476b-9022-079884b5d377)
But it doesn't exist - and `OK` gives this error:
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/2959112d-b3fc-40d4-bae7-4c6c2a874896)

2024-05-17 12:01 UTC, chrjorgensen commented on src/api/Tools.ts
> +  export function parseAttrDate(timestamp:string){
@sebjulliand This code is worrying me a bit - you get the attributes using the PASE command `attr`, which can return IBM i object attributes, but it writes the dates in text, which you then have to parse.

The timestamps output from `attr` are dependent on the locale, which may vary from system to system - or even user by user.

Wouldn't it be better to get the attributes for an IFS object using the[ SQL function](https://www.ibm.com/docs/en/i/7.3?topic=services-ifs-object-statistics-table-function) `IFS_OBJECT_STATISTICS`? It can return the same information and returns the timestamps in ISO format - or as EPOCH, if it is specified in the SQL statement. Like we do with member lists...

Then this parse function is irrelevant - and the month name at the top etc.

?

2024-05-17 21:34 UTC, sebjulliand commented on src/api/Tools.ts
> +  export function parseAttrDate(timestamp:string){
Well, I tried (hard) to use `IFS_OBJECT_STATISTICS`, but it doesn't give any information if you don't have enough authority to do so. Every column will be null in this case. For example, there are some files on PUB400 that I can access in read-only mode. For those, `IFS_OBJECT_STATISTICS` will not give me any information.

I tried on a few different LPARS and even when I change `LC_TIME` before calling `attr`, it still returns the dates using the en_US locale.

So for now, I'll take the risk of using `attr` and parse the dates empirically. 😅

2024-05-17 21:38 UTC, sebjulliand commented
@chrjorgensen I think I finally managed to fix Save As for your use case.
A file name ending with `.` is not valid when using Save As (VSCode doesn't allow it, there is no way around this). But, if you want to save as a member with no extension, just don't put an extension in the name; `QSYSFS` will now handle it correctly.

I had to change a bit `parserMemberPath` to do so, but it's for the best (hopefully).
You can give it another go whenever you want. Thanks!

2024-05-23 06:29 UTC, chrjorgensen reviewed
@sebjulliand The use case with no member extension does work now. 👍 

Only issue is that we require the "." when creating the member but require no "." when Save as... not consistent, but the opposite... but this is due to Microsoft not allowing file/directory names ending in "." in Windows where all other platforms allow it... 😠 

I also found that not having /QOpenSys/pkgs/bin in the PATH results in Save as reporting
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/8b1988f9-7317-4f63-8187-deb3c61f6ba1)
Adding the yum package directory to the path fixed the problem.

I will do some more testing... 😃

2024-05-23 06:56 UTC, chrjorgensen commented
There are still some issue with Save as reporting the error:
![billede](https://github.com/codefori/vscode-ibmi/assets/13275072/8b1988f9-7317-4f63-8187-deb3c61f6ba1)

When I as the first thing open a member for browse and choose Save as, I get the error. Open for edit does not show this error, and after open for edit, I can open for browse and use Save as... sometimes because often it accepts the save but does not actaully save...

2024-06-03 14:27 UTC, sebjulliand commented
@chrjorgensen give it another go. I removed the stat cache...hopefully the performance overhead won't be terrible.

2024-06-15 23:17 UTC, chrjorgensen requested changes
@sebjulliand Quick review while watching Le Mans... 😄 

Works alright when member is opened for edit - when opened for browse, the error `This folder cannot be used as destination. Please choose another folder.` is shown. If this cannot be avoided, maybe the Save As should reject the operation?

There is also an issue with member names with variants - I can't even open these members, even after merging master branch into the PR branch...? Can you make it work with variants?

Ideally the text of the new members should be set to the same as the original member - but this could be implemented in a future change.

2024-07-01 16:55 UTC, worksofliam commented
@sebjulliand What's the status here? Does it need a lil' TLC or can I review?

2024-07-01 19:55 UTC, sebjulliand commented
> @sebjulliand What's the status here? Does it need a lil' TLC or can I review?

@worksofliam I need to make some changes...this week of the week after 🥲

2024-09-03 20:33 UTC, sebjulliand commented
@chrjorgensen , it's back for review, finally 😅

>Works alright when member is opened for edit - when opened for browse, the error This folder cannot be used as destination. Please choose another folder. is shown.

I could get `Save As` to work for members/streamfiles opened in read-only mode. The only limitation is that the saved as member/file will still be opened in read-only because its URI share the same fragment as its "parent". I can't overcome this until we change the way our file systems handle the read-only flag (something I'll keep in the back of my head 😄).

> There is also an issue with member names with variants - I can't even open these members, even after merging master branch into the PR branch...? Can you make it work with **variants**

Done! Variant characters needed to be converted to  their CSSID 37 counterparts before being fed to the `attr` command. It works well now. Even creating a source file on the fly with variants!

> Ideally the text of the new members should be set to the same as the original member - but this could be implemented in a future change.

Sadly, I tried to find a way but since we cannot know which file is being saved as by the time the target is being created and written, we can't copy the description 😑

2024-09-23 15:36 UTC, julesyan approved these changes
I like it a lot. Code looks good to me. Tested locally with a variety of cases.

2024-09-25 11:52 UTC, sebjulliand commented
Thanks a lot for looking into this @julesyan ! Let's merge 😄

2024-09-25 11:52 UTC, merged