Added Keepalive interval login settings + fixed privatekeypath update
codefori/vscode-ibmi pull request #2077
Opened 2024-05-27 09:36 UTC by sebjulliand

### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/2074

This PR adds a new input to the Logins settings to let the user define a custom SSH `Keepalive interval`.
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/d72f2ede-d7d3-4a1b-b8d2-757d0807a3d0)

It also fixes an issue where the settings' `privateKeyPath` would be set to `''` instead of `undefined` after an update, making the connection process to crash afterwards.

### How to test this PR
Set a breakpoint in src/api/IBMi.ts on line 126.

1. Open an existing connection
2. Define a custom Keepalive interval
3. Connect
4. Check the `connectionObject.keepaliveInterval` field is set with the custom value.

### Checklist
* [x] have tested my change

2024-05-29 10:17 UTC, chrjorgensen commented
@sebjulliand Code works as expected - but the setting does not prevent the disconnect, unfortunately... 😞 

I'm not sure how or if we can fix #2069... would have thought the keepalive setting was the solution, but apparantly not...

Maybe you should break this PR into two PR and isolate the other fix for private key path in its own PR?

2024-05-29 11:07 UTC, sebjulliand commented
> Maybe you should break this PR into two PR and isolate the other fix for private key path in its own PR?
@chrjorgensen absolutely. I removed the private key fix from here and put it there: https://github.com/codefori/vscode-ibmi/pull/2082

2024-05-29 11:12 UTC, chrjorgensen commented
> absolutely. I removed the private key fix from here and put it there: #2082

@sebjulliand Great! I changed this PR to draft... when we find a solution we can continue here if necessary...

2024-06-04 15:33 UTC, worksofliam requested changes
Like I said, not very good. Work on this more.

2024-06-09 22:15 UTC, worksofliam commented
@sebjulliand is this actually ready to be reviewed?

2024-06-10 10:01 UTC, sebjulliand commented
@worksofliam welp, it was changed to draft since it doesn't seem to fix the original issue, even though the keepalive is adjusted (checkout @chrjorgensen comment above).

2024-06-10 10:28 UTC, worksofliam commented
@sebjulliand I suspect it's also related to the timeout as set by the OS. @chrjorgensen What do you see with `CHGTCPA`? I believe there is a timeout option there too which might be similar.

2025-01-18 15:11 UTC, closed without merging