Fix and test case for supporting members with dollar signs
codefori/vscode-ibmi pull request #2191
Opened 2024-07-23 14:14 UTC by worksofliam

### Changes

Fixes #2177 by not escaping at the right time.

* A new test case with members with dollar signs in the name has been added
* Renamed `sanitise` to `noEscape` to make more sense based on the existing code logic

### How to test this PR

Examples:

1. Run the test cases
2. Try creating and editing a member with a dollar sign

### Checklist

* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-07-23 14:17 UTC, worksofliam commented
It seems like there might be some contention between where the encoding actually happens. I am passing `true` to `qualifyPath` so it doesn't escape:

https://github.com/codefori/vscode-ibmi/blob/fix/dollars_in_names/src/api/IBMiContent.ts#L152

As I am expecting it to be escaped in the `runCommand` function: https://github.com/codefori/vscode-ibmi/blob/fix/dollars_in_names/src/api/CompileTools.ts#L681

2024-08-05 16:36 UTC, sebjulliand requested changes
Code looks good to me. Replacing `sanitize` with `noEscape` is great...makes a lot more sense!
See my remark about that line being removed though.

2024-08-05 16:36 UTC, sebjulliand commented on src/api/IBMiContent.ts
> -                retry = true;
Why have you removed `retry = true` here?

2024-08-05 18:02 UTC, worksofliam commented
@sebjulliand Not sure why I did that. Re-requested your review.

2024-08-05 19:02 UTC, sebjulliand approved these changes
Approved and good to go!

2024-08-05 19:02 UTC, merged