Remove SEU colour support
codefori/vscode-ibmi pull request #2192
Opened 2024-07-23 14:23 UTC by worksofliam

### Changes

Removes all logic tied to SEU/5250 colours. See #2057 for more information.

Closes #2056

### How to test this PR

1. Open and edit source members in SQL mode

### Checklist

* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

2024-11-27 20:28 UTC, sebjulliand requested changes
There is just a missing localised string; otherwise it looks good. And the code is cleaner!

2024-11-27 20:28 UTC, sebjulliand commented on src/languages/colour.ts
> +    l10n.t(`seuColours.warning`),
This was lost after migration to l10n
```suggestion
    l10n.t("This member contains invalid characters. Would you like to clean it up?"), 
```

2024-11-27 21:00 UTC, sebjulliand commented
Look how funny it is!
![image](https://github.com/user-attachments/assets/d62db9b8-f375-4feb-83a0-edbb8329b868)

2024-12-18 13:52 UTC, sebjulliand commented
> @sebjulliand So it looks like the characters get converted differently based on whether source dates is enabled or disabled (e.g. fetching the contents with SQL or `CPYTOSTMF`).
> 
> What do you think we should do? Should we try and support both cases?

I'm afraid so 🙄

2024-12-18 14:14 UTC, worksofliam commented
@sebjulliand I am actually think we need to do this outside of the file system providers and perhaps instead use @chrjorgensen's SQL procedure to handle the logic.

It could be embedded as a component, or we could point users there. Writing the logic twice over for two file systems might not be in our interest.

2025-01-25 18:39 UTC, worksofliam commented
Will close this and re-open due to cleanup.

2025-01-25 18:42 UTC, closed without merging