Fix `Search Source File` crahsing when used with a complex filter
codefori/vscode-ibmi pull request #2213
Opened 2024-08-03 16:07 UTC by sebjulliand

### Changes
Fixes https://github.com/codefori/vscode-ibmi/issues/2207

Searching for text in members of a source file would crash if run on a "complex" filter. By complex, I mean a filter whose member filtering term is either a Regex or not a single generic name (`XXX*`).

This PR fixes this issue, making sure the search runs fine in all cases.
It also fixes some minor issues:
- The search progress message was still `Listing members...` even after the listing was done and `grep` was running
- The position used when opening a search hit could be wrong if the line started with one or more whitespaces
- The interval set for displaying different messages during the search was not cleared immediately when the search was over

### How to test this PR
1. Run a search on a simple filter
2. Run a search on a complex filter

In both cases, the results must be as expected and only the members actually listed by the filter must be shown in the search result.

### Checklist
* [x] have tested my change

2024-08-03 18:13 UTC, worksofliam commented
I will review over the next day or two. Is it worth creating or updating any test cases for this fix?

2024-08-03 18:57 UTC, worksofliam requested changes
Left some comments. I personally need more context to understand the purpose of this additional property (sorry!)

2024-08-03 18:57 UTC, worksofliam commented on src/api/IBMi.ts
> +            this.maximumArgsLength = Number((await this.sendCommand({ command: "expr `getconf ARG_MAX` - `env|wc -c` - `env|wc -l` \\* 4 - 2048" })).stdout);
Some thoughts here:

1. Is this assuming bash is the default?
2. Should we use explicit paths to `expr` and `getconf`?

2024-08-03 18:57 UTC, worksofliam commented on src/api/IBMi.ts
> +  maximumArgsLength = 0;
Some commands on the purpose of this new property might be good.

2024-08-03 19:15 UTC, sebjulliand commented on src/api/IBMi.ts
> +            this.maximumArgsLength = Number((await this.sendCommand({ command: "expr `getconf ARG_MAX` - `env|wc -c` - `env|wc -l` \\* 4 - 2048" })).stdout);
1. No, it seems to work from QSH as well.
2. Both are found under `/QOpenSys/usr/bin` and I assume they are always here. But making their path absolute won't hurt 😊

2024-08-03 19:18 UTC, sebjulliand commented on src/api/IBMi.ts
> +  maximumArgsLength = 0;
Yep. Basically, my biggest concern with the change I made to the search API was that there was a risk to issue a command that would be too long for the shell to process. So I looked if an actual limit existed and how to find it. And there it was.
So this property is the maximum admitted length for a command's arguments.

I use it in the search API to prevent an error in case the `grep` built to search is too long to be run. I put a comment in the search API but I'll add one here too.

2024-08-03 21:41 UTC, sebjulliand commented
> I will review over the next day or two. Is it worth creating or updating any test cases for this fix?

Here, have a few tests 😊

2024-08-05 14:12 UTC, worksofliam approved these changes

2024-08-21 16:51 UTC, merged