Made Java installation as connection features
codefori/vscode-ibmi pull request #2283
Opened 2024-10-07 20:21 UTC by sebjulliand

### Changes
This PR takes the Java discovery part of https://github.com/codefori/vscode-ibmi/pull/2195.
The different possible Java installation locations are made into connection features.

These features are now used to get Java Home path when configuring the debug service.

### How to test this PR
1. Run the Debug test case
2. Generate a Debug Service certificate
3. Check Java Home in the Debug Service configuration file

### Checklist
* [x] have tested my change

2024-10-07 21:14 UTC, worksofliam commented
Beautiful code change. Will get it tested ASAP.

2024-10-08 16:02 UTC, worksofliam commented on src/api/IBMi.ts
> +            this.remoteFeatures.jdk80 = await javaCheck(`/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit`);
Just being specific. Should this be `jdk08` or is `jdk80` ok?

2024-10-08 16:06 UTC, worksofliam commented on src/api/IBMi.ts
> +            const javaCheck = async (root: string) => await this.content.testStreamFile(`${root}/bin/java`, 'x') ? `${root}` : undefined;
Just a note: I had to connect and reload for this to be hit.

2024-10-08 16:09 UTC, worksofliam requested changes
I think my only concern is the finding of JDK version without reloading. Other than that, very nice change!

2024-10-08 16:50 UTC, sebjulliand commented on src/api/IBMi.ts
> +            this.remoteFeatures.jdk80 = await javaCheck(`/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit`);
`jdk80` it is.
![image](https://github.com/user-attachments/assets/acee8980-a79d-4424-ad1a-e7ea5151eeec)

2024-10-08 17:00 UTC, sebjulliand commented
> I think my only concern is the finding of JDK version without reloading. Other than that, very nice change!

@worksofliam Can you try again? I connected to an existing system created and connected before the PR, and the reloading occurred as expected.

The existing test was accurate:
![image](https://github.com/user-attachments/assets/f0d376fa-4889-486f-a0d6-7521780f9ed3)

Or am I missing something obvious? 😅

2024-10-09 14:12 UTC, worksofliam approved these changes
@sebjulliand Tested again and it worked as expected. I connected to an existing system and it grabbed the JDK correctly. Thanks!

Merge away!

2024-10-09 14:27 UTC, merged