Add Auto Reconnect setting
codefori/vscode-ibmi pull request #2326
Opened 2024-11-03 22:15 UTC by sebjulliand

### Changes
Resolves #2300 

Based on @p-behr suggestion, this PR adds a new global settings that sets the action taken out by Code for i when a member/streamfile is left open when VS Code is closed and re-opened.

![image](https://github.com/user-attachments/assets/874186a6-9b07-44c5-a546-e01852568c0b)

Supported values are:
* `ask`: opens a notification asking whether or not the user wants to reconnect
![image](https://github.com/user-attachments/assets/491a1cf5-68bb-4fb4-a460-a25add190f34)
* `always`: always reconnect
* `never`: never reconnect

If the user choose to reconnect, the member/streamfile is reloaded. Otherwise, the editor that was left open is closed.

### How to test this PR
1. Open a member/streamfile
2. Leave it open and close VS Code
3. Re-open VS Code
4. Based on the reconnect setting, code for i will reconnect, close the editor or ask the user if they want to reconnect

### Checklist
* [x] have tested my change

2024-11-06 20:05 UTC, worksofliam requested changes
I very much like this PR, but I think the message should show what system they're reconnecting to.

> Do you want to reconnect to SYSTEM and open FILE?

2024-11-06 20:05 UTC, worksofliam commented on src/filesystems/qsys/FSUtils.ts
> +      if (await vscode.window.showInformationMessage(l10n.t("Do you want to reconnect and open {0}?", uri.path.split('/').reverse()?.[0]), l10n.t("Reconnect"))) {
Perhaps `path.basename(uri.path)` might be more suited?

2024-11-06 20:56 UTC, sebjulliand commented on src/filesystems/qsys/FSUtils.ts
> +      if (await vscode.window.showInformationMessage(l10n.t("Do you want to reconnect and open {0}?", uri.path.split('/').reverse()?.[0]), l10n.t("Reconnect"))) {
Yes, that's way less clunky 😅

2024-11-06 21:01 UTC, sebjulliand commented
There you go @worksofliam. It's all yours for a final review.
![image](https://github.com/user-attachments/assets/d1e46393-a4a8-4f04-a940-576653a426b1)

2024-11-06 21:01 UTC, sebjulliand commented on src/filesystems/qsys/FSUtils.ts
> +      if (await vscode.window.showInformationMessage(l10n.t("Do you want to reconnect and open {0}?", uri.path.split('/').reverse()?.[0]), l10n.t("Reconnect"))) {
Yes, that's way less clunky 😅

2024-11-06 21:10 UTC, worksofliam approved these changes
Working good! I will let you merge :)

2024-11-06 21:12 UTC, merged

2024-12-11 15:22 UTC, p-behr commented
This is terrific, thanks @sebjulliand

2024-12-11 15:24 UTC, sebjulliand commented
> This is terrific, thanks @sebjulliand

My pleasure 🙏🏻