Add encoding tests for CCSID handling
codefori/vscode-ibmi pull request #2334
Opened 2024-11-08 17:39 UTC by worksofliam

Improved support for variant characters no matter the QCCSID. This has been impossible for us to test in the pass due to us not fetching the variants correctly before - which I have fixed in this PR - and now VS Code is correctly picking up the variants based on the user profile CCSID. This solves things like:

* Browsing the QSYS file system when libraries and source files have variants in the name
* Opening members with variants in the name
* Running ILE commands with variants in them
* Running SQL statements with variants in the statement

Many test cases were worked on under the Encoding suite and they are all passing, showing that we can now work with variants.

## Changes

* Introduces new component, `cqsh`, which wraps `_SETCCSID` and `qsh` together since `qsh` always ignores user CCSID when launching from a non-interactive shell. **We need to update our docs with info about this!**
* `runSQL` now uses `cqsh` when available as it solves issues with variant characters in the statement and in the result set
* `runSQL` now determines if CSVs are needed based on the availability of `cqsh` and CCSID
* `runCommand` and `runSql` can now take care of variants instead of letting the callers deal with it
* Changes when variant characters are fetched (always towards the end)
* `getObjectList` now using `for bit data` on source files
* `validateLibraryList` now supports variant names
* Fixes to when `$` is escaped (also added generic function `IBMi.escapeForShell`)
* Convert `IBMi#dangerousVariants` into getter instead of class property

### Changes not related to the fix

* Add additional parameter to `runSQL` to allow for pseudo parameters, which automatically take care of encoding the input to ensure it's passed the OS correctly
* Added the ability to run test suites simultaneously & on a specific fixture
* Fix test 'check getMemberInfo' which has been broken since we introduced components
* Remove some invalid tests for testing `getTable` without `enableSQL` property
* Improved the PR workflow to run every commit and not spam new comments for each build, but instead update an existing comment.
* Ability to define different fixtures against the same system

## Testing

With the introduction with fixtures, we can now easily switch between consistent profiles on a connection. This PR has been tested against all fixtures (American, Danish, Spanish, French) and all tests are passing.

* [x] Solve 'Test downloadMemberContent with dollar' with Danish
* [ ] Solve 'download' against a source file when variant char is used (this logic is embedded in the Object Browser)
* [ ] Ensure tests are passing on PUB400.
* [ ] Ensure tests are passing on 7.3
* [x] Ensure tests are passing on 7.4/7.5

2024-11-08 17:44 UTC, worksofliam commented
I am working on a test case.

2024-11-10 18:22 UTC, worksofliam commented
In theory, the new test case added that checks variants should be able to run no matter the QCCSID or runtime CCSID.

2024-11-12 19:12 UTC, e1mais commented
Hi @worksofliam 

I just downloaded the pre-release version of code for IBM i, and also did the connect and reload server settings, but I still see a '#' instead of 'Ñ'on the where clause of the SQL in OUTPUT when I'm expanding the source file

2024-11-12 19:25 UTC, worksofliam commented
@e1mais you will continue to see the #, but does the list load or not?

2024-11-12 19:30 UTC, e1mais commented
@worksofliam the list does not load :(

2024-11-12 19:35 UTC, worksofliam commented
@e1mais Can I interest you in meeting with me to have a look at this issue? Sadly, with the same setup I am not having these issues. If you are, please reach out to me on LinkedIn: https://www.linkedin.com/in/worksofbarry/

2024-11-12 19:50 UTC, e1mais commented
@worksofliam It would be a great help. But I can't message you on LinkedIn because I'm not premium:(

But this is my profile: https://www.linkedin.com/in/ismael-alexander-martínez-villalta-52061a230

2024-11-25 15:56 UTC, SanjulaGanepola commented on src/testing/index.ts
> +          vscode.commands.executeCommand(`code-for-ibmi.connectTo`, connectionName, true);
Shouldn't we be calling `code-for-ibmi.connectToAndReload` here to pick up the CCSID change?

2024-11-25 15:56 UTC, worksofliam commented on src/testing/index.ts
> +          vscode.commands.executeCommand(`code-for-ibmi.connectTo`, connectionName, true);
@SanjulaGanepola The `true` parameter also does the same thing.

2024-11-25 15:57 UTC, SanjulaGanepola commented on src/testing/index.ts
> +          vscode.commands.executeCommand(`code-for-ibmi.connectTo`, connectionName, true);
Oh completely missed that.

2024-11-25 15:59 UTC, worksofliam commented on src/testing/encoding.ts
> +      name: "Listing objects with variants",
@SanjulaGanepola I am not able to recreate this with `Spanish 284, ES, ESP`:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/51521ed0-e279-47f1-9100-fafe6e3c3478">

2024-11-25 16:14 UTC, worksofliam commented on src/testing/encoding.ts
>        name: `Encoding ${ccsid}`, test: async () => {
Solved in new commit.

2024-11-25 16:14 UTC, worksofliam commented on src/api/IBMiContent.ts
> +    const command = `for f in ${directories.flatMap(dir => names.map(name => `"${Tools.escapePath(path.posix.join(dir, name))}"`)).join(` `)}; do if [ -f "$f" ]; then echo $f; break; fi; done`;
Solved in new commit.

2024-11-25 16:41 UTC, worksofliam commented on src/testing/encoding.ts
>        name: `Encoding ${ccsid}`, test: async () => {
Fixed in new commit.

2024-11-25 17:00 UTC, SanjulaGanepola requested changes

2024-11-25 17:00 UTC, SanjulaGanepola commented on src/api/IBMi.ts
> +            if (this.getComponent(cqsh)) {
For consistency with other places where this is used:
```suggestion
            if (this.canUseCqsh) {
```

2024-11-25 17:00 UTC, SanjulaGanepola commented on src/api/IBMi.ts
> +            if (!this.canUseCqsh) {
With the above change:
```suggestion
            else {
```

2024-11-25 17:00 UTC, SanjulaGanepola commented on src/api/IBMi.ts
> +              vscode.window.showWarningMessage(`The job CCSID is set to 65535. This may cause issues with objects with variant characters. Please use CHGUSRPRF USER(${this.currentUser.toUpperCase()})
```suggestion
              vscode.window.showWarningMessage(`The job CCSID is set to ${CCSID_NOCONVERSION}. This may cause issues with objects with variant characters. Please use CHGUSRPRF USER(${this.currentUser.toUpperCase()}) CCSID(${this.userDefaultCCSID}) to set your profile to the current default CCSID.`, `Show documentation`).then(choice => {
```

2024-11-25 17:00 UTC, SanjulaGanepola commented on src/api/IBMi.ts
> +      commands.push(...Object.entries(options.env).map(([key, value]) => `export ${key}="${value ? IBMi.escapeForShell(value) : ``}"`));
Question: Do you no longer have to escape double quotes like you previously did here?

2024-11-25 17:43 UTC, worksofliam commented on src/api/IBMi.ts
> +      commands.push(...Object.entries(options.env).map(([key, value]) => `export ${key}="${value ? IBMi.escapeForShell(value) : ``}"`));
We still need the double quote here as this uses `escapeForShell` and not `escapePath` (which is what I just fixed in the recent commit.)

2024-11-25 18:03 UTC, SanjulaGanepola requested changes

2024-11-25 18:03 UTC, SanjulaGanepola commented on package.json
> +				"enablement": "code-for-ibmi:testing"
This enablement condition `code-for-ibmi:testing` should be moved to the commands `when` clause or this will also be shown in production!

![image](https://github.com/user-attachments/assets/8f485b2b-0ff1-4701-affb-7d7121f45ea2)

2024-11-25 18:21 UTC, SanjulaGanepola commented on src/testing/encoding.ts
> +      name: "Listing objects with variants",
After debugging `Listing objects with variants`, it is failing at

```ts
const result = await runCommandsWithCCSID(connection, commands, ccsid);
```
during the compile step. When I run it manually

![image](https://github.com/user-attachments/assets/a0525a1e-bef4-45be-90a6-dfb12a7b0233)

this is a portion of the output:

![image](https://github.com/user-attachments/assets/679b9cee-5144-4c90-984f-dfe43060edbb)

2024-11-25 18:36 UTC, worksofliam commented on src/testing/encoding.ts
> +      name: "Listing objects with variants",
@SanjulaGanepola to me it seems like the variant chars aren't set correctly for Spanish.

Before that is executed, can you share the contents of `connection.variantChars`?

2024-11-25 18:42 UTC, SanjulaGanepola commented on src/testing/encoding.ts
> +      name: "Listing objects with variants",
![image](https://github.com/user-attachments/assets/709ee320-786f-45bc-9c17-a9839386b809)

2024-11-25 21:13 UTC, worksofliam commented on src/testing/encoding.ts
> +      name: "Listing objects with variants",
Fixed in new commit.

2024-11-25 21:19 UTC, SanjulaGanepola commented on src/api/IBMi.ts
> +            const systemVersionResult = await this.sendCommand({ command: `/QOpenSys/usr/bin/uname -rv` });
Minor suggestion: 
```suggestion
            const systemVersionResult = await this.sendCommand({ command: `${this.remoteFeatures.uname} -rv` });
```

2024-11-25 21:20 UTC, worksofliam commented on src/api/IBMiContent.ts
> +    newLibl = newLibl
Yes, I believe this to be a good idea, but should be done in a separate PR just for the fact that we have the tests passing as it is now.

2024-11-25 21:20 UTC, worksofliam commented on src/api/IBMiContent.ts
> +    newLibl = newLibl
https://github.com/codefori/vscode-ibmi/issues/2366

2024-11-25 21:21 UTC, SanjulaGanepola commented on src/api/IBMiContent.ts
> +    newLibl = newLibl
Agreed!

2024-11-25 22:52 UTC, worksofliam commented
@SanjulaGanepola I need you to review one last time with my added commit. There are two new test cases to ensure streamfiles works with certain characters (`#` and `$`). Thanks!

2024-11-26 14:25 UTC, merged